export interface CampaignLayout {
  readonly id: number;
  readonly title: string;
  readonly gridSize: number;
  readonly lives: number;
  readonly arrowIds: readonly string[];
}

/** Frozen authoring output. IDs encode each exact route recipe; no search runs in play. */
export const CAMPAIGN_LAYOUTS: readonly CampaignLayout[] = [
  {
    id: 2,
    title: "Cube 2",
    gridSize: 4,
    lives: 5,
    arrowIds: [
      "l2-front-dependency-blocked",
      "l2-front-dependency-clear",
      "l2-wrap-top-west-3-1",
      "l2-wrap-front-west-3-1",
      "l2-straight-back-east-0-2",
      "l2-straight-right-east-0-2",
      "l2-straight-bottom-east-0-2",
      "l2-straight-front-east-2-2",
      "l2-straight-front-west-1-3",
      "l2-straight-back-east-1-4",
      "l2-straight-back-east-2-4",
      "l2-straight-back-east-3-4",
    ],
  },
  {
    id: 3,
    title: "Cube 3",
    gridSize: 5,
    lives: 5,
    arrowIds: [
      "l3-front-dependency-a",
      "l3-front-dependency-b",
      "l3-front-dependency-c",
      "l3-wrap-top-west-4-1",
      "l3-wrap-front-west-4-1",
      "l3-straight-back-east-0-2",
      "l3-straight-right-east-0-2",
      "l3-straight-bottom-east-0-2",
      "l3-straight-front-east-2-2",
      "l3-straight-front-east-3-3",
      "l3-straight-front-west-1-4",
      "l3-straight-back-east-1-5",
      "l3-bend-back-east-3",
      "l3-bend-back-south-0",
      "l3-bend-right-east-1",
      "l3-bend-right-east-3",
    ],
  },
  {
    id: 4,
    title: "Cube 4",
    gridSize: 5,
    lives: 4,
    arrowIds: [
      "l4-front-dependency-a",
      "l4-front-dependency-b",
      "l4-front-dependency-c",
      "l4-wrap-top-west-4-1",
      "l4-wrap-front-west-4-1",
      "l4-straight-back-east-0-2",
      "l4-straight-right-east-0-2",
      "l4-straight-bottom-east-0-2",
      "l4-straight-front-east-2-2",
      "l4-straight-front-east-3-3",
      "l4-straight-front-west-1-4",
      "l4-straight-back-east-1-5",
      "l4-bend-back-east-3",
      "l4-bend-back-south-0",
      "l4-bend-right-east-1",
      "l4-bend-right-east-3",
      "l4-bend-right-south-0",
      "l4-bend-left-east-2",
      "l4-bend-top-east-0",
      "l4-bend-top-east-3",
    ],
  },
  {
    id: 5,
    title: "Cube 5",
    gridSize: 6,
    lives: 4,
    arrowIds: [
      "l5-front-dependency-a",
      "l5-front-dependency-b",
      "l5-front-dependency-c",
      "l5-wrap-top-west-5-2",
      "l5-wrap-front-west-5-1",
      "l5-wrap-front-east-2-1",
      "l5-wrap-front-east-3-1",
      "l5-wrap-front-east-4-1",
      "l5-wrap-front-east-5-1",
      "l5-straight-bottom-east-0-2",
      "l5-straight-front-west-1-2",
      "l5-straight-front-west-2-3",
      "l5-straight-front-west-3-4",
      "l5-straight-back-east-1-5",
      "l5-bend-back-east-3",
      "l5-bend-back-east-5",
      "l5-bend-back-west-3",
      "l5-bend-back-west-5",
      "l5-bend-right-east-0",
      "l5-bend-right-west-0",
      "l5-bend-left-east-2",
      "l5-bend-left-east-4",
      "l5-bend-left-west-2",
      "l5-bend-left-west-4",
    ],
  },
  {
    id: 6,
    title: "Cube 6",
    gridSize: 6,
    lives: 4,
    arrowIds: [
      "l6-front-dependency-a",
      "l6-front-dependency-b",
      "l6-front-dependency-c",
      "l6-wrap-top-west-5-2",
      "l6-wrap-front-west-5-1",
      "l6-wrap-front-east-2-1",
      "l6-wrap-front-east-3-1",
      "l6-wrap-front-east-4-1",
      "l6-wrap-front-east-5-1",
      "l6-wrap-front-west-1-1",
      "l6-straight-bottom-east-0-2",
      "l6-straight-front-west-2-2",
      "l6-straight-front-west-3-3",
      "l6-straight-front-west-4-4",
      "l6-straight-back-east-1-5",
      "l6-bend-back-east-3",
      "l6-bend-back-east-5",
      "l6-bend-back-west-3",
      "l6-bend-back-west-5",
      "l6-bend-right-east-0",
      "l6-bend-right-west-0",
      "l6-bend-left-east-3",
      "l6-bend-left-west-3",
      "l6-bend-top-east-0",
      "l6-bend-top-east-3",
      "l6-bend-top-east-5",
      "l6-bend-top-west-0",
      "l6-bend-top-west-3",
    ],
  },
  {
    id: 7,
    title: "Cube 7",
    gridSize: 6,
    lives: 3,
    arrowIds: [
      "l7-front-dependency-a",
      "l7-front-dependency-b",
      "l7-front-dependency-c",
      "l7-top-dependency-a",
      "l7-top-dependency-b",
      "l7-top-dependency-c",
      "l7-left-dependency-a",
      "l7-left-dependency-b",
      "l7-left-dependency-c",
      "l7-wrap-front-west-5-2",
      "l7-wrap-front-north-5-1",
      "l7-wrap-front-east-2-1",
      "l7-wrap-front-east-3-1",
      "l7-wrap-front-east-4-1",
      "l7-wrap-front-east-5-1",
      "l7-wrap-front-west-2-1",
      "l7-wrap-front-west-3-1",
      "l7-straight-bottom-east-0-2",
      "l7-straight-front-west-1-2",
      "l7-straight-front-west-4-3",
      "l7-straight-front-south-3-4",
      "l7-straight-back-east-0-5",
      "l7-bend-back-east-2",
      "l7-bend-back-east-4",
      "l7-bend-back-west-2",
      "l7-bend-back-west-4",
      "l7-bend-right-east-0",
      "l7-bend-right-west-0",
      "l7-bend-top-east-2",
      "l7-bend-top-east-4",
      "l7-bend-top-west-2",
      "l7-bend-top-west-4",
    ],
  },
  {
    id: 8,
    title: "Cube 8",
    gridSize: 7,
    lives: 3,
    arrowIds: [
      "l8-front-dependency-a",
      "l8-front-dependency-b",
      "l8-front-dependency-c",
      "l8-top-dependency-a",
      "l8-top-dependency-b",
      "l8-top-dependency-c",
      "l8-left-dependency-a",
      "l8-left-dependency-b",
      "l8-left-dependency-c",
      "l8-wrap-front-west-6-2",
      "l8-wrap-front-north-6-1",
      "l8-wrap-front-east-2-1",
      "l8-wrap-front-east-3-1",
      "l8-wrap-front-east-4-1",
      "l8-wrap-front-east-5-1",
      "l8-wrap-front-east-6-1",
      "l8-wrap-front-west-2-1",
      "l8-wrap-front-west-3-1",
      "l8-straight-bottom-east-0-2",
      "l8-straight-front-west-1-2",
      "l8-straight-front-west-4-3",
      "l8-straight-front-west-5-4",
      "l8-straight-front-south-4-5",
      "l8-bend-back-east-0",
      "l8-bend-back-east-3",
      "l8-bend-back-east-5",
      "l8-bend-back-west-0",
      "l8-bend-back-west-3",
      "l8-bend-back-west-5",
      "l8-bend-right-east-0",
      "l8-bend-right-west-0",
      "l8-bend-left-east-5",
      "l8-bend-left-west-5",
      "l8-bend-top-east-3",
      "l8-bend-top-east-5",
      "l8-bend-top-west-2",
    ],
  },
  {
    id: 9,
    title: "Cube 9",
    gridSize: 8,
    lives: 3,
    arrowIds: [
      "l9-front-dependency-a",
      "l9-front-dependency-b",
      "l9-front-dependency-c",
      "l9-top-dependency-a",
      "l9-top-dependency-b",
      "l9-top-dependency-c",
      "l9-left-dependency-a",
      "l9-left-dependency-b",
      "l9-left-dependency-c",
      "l9-wrap-front-west-7-2",
      "l9-wrap-front-north-7-1",
      "l9-wrap-front-east-2-1",
      "l9-wrap-front-east-3-1",
      "l9-wrap-front-east-4-1",
      "l9-wrap-front-east-5-1",
      "l9-wrap-front-east-6-1",
      "l9-wrap-front-east-7-1",
      "l9-wrap-front-west-2-1",
      "l9-wrap-front-west-3-1",
      "l9-straight-bottom-east-0-2",
      "l9-straight-front-west-1-2",
      "l9-straight-front-west-4-3",
      "l9-straight-front-west-5-4",
      "l9-straight-front-west-6-5",
      "l9-bend-back-east-0",
      "l9-bend-back-east-3",
      "l9-bend-back-east-5",
      "l9-bend-back-west-0",
      "l9-bend-back-west-3",
      "l9-bend-back-west-5",
      "l9-bend-back-north-3",
      "l9-bend-right-east-0",
      "l9-bend-right-west-0",
      "l9-bend-left-east-0",
      "l9-bend-left-east-5",
      "l9-bend-left-west-5",
      "l9-bend-top-east-0",
      "l9-bend-top-east-3",
      "l9-bend-top-east-5",
      "l9-bend-top-west-2",
    ],
  },
  {
    id: 10,
    title: "Cube 10",
    gridSize: 8,
    lives: 3,
    arrowIds: [
      "l10-front-dependency-a",
      "l10-front-dependency-b",
      "l10-front-dependency-c",
      "l10-top-dependency-a",
      "l10-top-dependency-b",
      "l10-top-dependency-c",
      "l10-left-dependency-a",
      "l10-left-dependency-b",
      "l10-left-dependency-c",
      "l10-wrap-front-west-7-2",
      "l10-wrap-front-north-7-1",
      "l10-wrap-front-east-2-1",
      "l10-wrap-front-east-3-1",
      "l10-wrap-front-east-4-1",
      "l10-wrap-front-east-5-1",
      "l10-wrap-front-east-6-1",
      "l10-wrap-front-east-7-1",
      "l10-wrap-front-west-2-1",
      "l10-wrap-front-west-3-1",
      "l10-wrap-front-west-4-1",
      "l10-straight-bottom-east-0-2",
      "l10-straight-front-west-1-2",
      "l10-straight-front-west-5-3",
      "l10-straight-front-west-6-4",
      "l10-straight-front-south-4-5",
      "l10-bend-back-east-0",
      "l10-bend-back-east-3",
      "l10-bend-back-east-5",
      "l10-bend-back-west-0",
      "l10-bend-back-west-3",
      "l10-bend-back-west-5",
      "l10-bend-back-north-3",
      "l10-bend-right-east-0",
      "l10-bend-right-west-0",
      "l10-bend-left-east-0",
      "l10-bend-left-east-6",
      "l10-bend-left-west-6",
      "l10-bend-top-east-0",
      "l10-bend-top-east-3",
      "l10-bend-top-east-5",
      "l10-bend-top-west-2",
      "l10-bend-top-west-4",
    ],
  },
];
