import { stepSurface } from "../core/topology";
import type { Cell, FaceId, Heading, LevelDefinition } from "../core/types";

export interface FrozenRoute {
  readonly id: string;
  readonly start: readonly [FaceId, number, number];
  readonly steps: string;
}
interface FrozenLayout {
  readonly id: number;
  readonly title: string;
  readonly gridSize: number;
  readonly lives: number;
  readonly routes: readonly FrozenRoute[];
}

const HEADING: Readonly<Record<string, Heading>> = {
  E: "east",
  W: "west",
  S: "south",
  N: "north",
};

export function decodeRoute(
  route: FrozenRoute,
  gridSize: number,
): readonly Cell[] {
  let current: Cell = {
    face: route.start[0],
    x: route.start[1],
    y: route.start[2],
  };
  const path: Cell[] = [current];
  for (const token of route.steps) {
    const heading = HEADING[token];
    if (!heading)
      throw new Error(
        `Frozen route ${route.id} has an invalid direction token.`,
      );
    current = stepSurface(current, heading, gridSize);
    path.push(current);
  }
  return path;
}

const FROZEN_LAYOUTS: readonly FrozenLayout[] = [
  {
    id: 2,
    title: "Cube 2",
    gridSize: 8,
    lives: 5,
    routes: [
      { id: "l2-bottom-three-cell-line", start: ["bottom", 5, 7], steps: "EE" },
      { id: "l2-top-two-cell-line", start: ["top", 1, 7], steps: "W" },
      { id: "l2-top-wrap-west-6", start: ["top", 1, 6], steps: "WWSSSSSSS" },
      {
        id: "l2-front-wrap-north-6",
        start: ["front", 6, 1],
        steps: "NNNNNNNNN",
      },
      {
        id: "l2-right-wrap-east-6",
        start: ["right", 6, 6],
        steps: "EEEEEEEEE",
      },
      { id: "l2-left-wrap-south-5", start: ["left", 5, 6], steps: "SSEEEEEEE" },
      { id: "l2-front-left-0-inward", start: ["front", 0, 0], steps: "ESESE" },
      { id: "l2-front-right-1", start: ["front", 4, 3], steps: "EEESWWWSEEE" },
      {
        id: "l2-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l2-front-east-line", start: ["front", 0, 6], steps: "EEEEEEE" },
      { id: "l2-back-right-0", start: ["back", 4, 0], steps: "EEESWWWSEEE" },
      {
        id: "l2-back-left-0-inward",
        start: ["back", 0, 2],
        steps: "EEENWWWNEEE",
      },
      { id: "l2-back-right-1", start: ["back", 4, 3], steps: "EEESWWWSEEE" },
      {
        id: "l2-back-left-1-inward",
        start: ["back", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l2-right-right-0", start: ["right", 4, 0], steps: "ESESE" },
      { id: "l2-right-left-0-inward", start: ["right", 0, 0], steps: "ESESW" },
      { id: "l2-right-right-1", start: ["right", 4, 3], steps: "EEESWWWSEEE" },
      {
        id: "l2-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l2-right-west-line", start: ["right", 3, 6], steps: "WWW" },
      { id: "l2-left-left-0-inward", start: ["left", 0, 0], steps: "ESESE" },
      {
        id: "l2-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l2-left-west-line", start: ["left", 3, 6], steps: "WWW" },
      {
        id: "l2-top-left-0-inward",
        start: ["top", 0, 2],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l2-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l2-bottom-right-1",
        start: ["bottom", 4, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l2-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l2-bottom-east-line", start: ["bottom", 0, 6], steps: "EEEEEEE" },
      { id: "l2-left-hook-fill-84", start: ["left", 5, 3], steps: "NWNWN" },
      { id: "l2-front-edge-fill-155", start: ["front", 4, 2], steps: "EEE" },
      { id: "l2-front-edge-fill-174", start: ["front", 3, 7], steps: "WWW" },
    ],
  },
  {
    id: 3,
    title: "Cube 3",
    gridSize: 9,
    lives: 5,
    routes: [
      { id: "l3-front-chain-a", start: ["front", 0, 8], steps: "E" },
      { id: "l3-front-chain-b", start: ["front", 2, 8], steps: "E" },
      { id: "l3-front-chain-c", start: ["front", 4, 8], steps: "E" },
      { id: "l3-bottom-three-cell-line", start: ["bottom", 6, 8], steps: "EE" },
      { id: "l3-top-two-cell-line", start: ["top", 1, 8], steps: "W" },
      { id: "l3-top-wrap-west-7", start: ["top", 1, 7], steps: "WWSSSSSSSS" },
      {
        id: "l3-front-wrap-north-7",
        start: ["front", 7, 1],
        steps: "NNNNNNNNNN",
      },
      {
        id: "l3-right-wrap-east-7",
        start: ["right", 7, 7],
        steps: "EEEEEEEEEE",
      },
      {
        id: "l3-left-wrap-south-6",
        start: ["left", 6, 7],
        steps: "SSEEEEEEEE",
      },
      {
        id: "l3-front-left-0-inward",
        start: ["front", 0, 2],
        steps: "EEENWWWNEEE",
      },
      { id: "l3-front-right-1", start: ["front", 5, 3], steps: "EEESWWWSEEE" },
      {
        id: "l3-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l3-front-east-line", start: ["front", 1, 6], steps: "EEEEEEE" },
      { id: "l3-back-right-0", start: ["back", 5, 0], steps: "ESESE" },
      { id: "l3-back-left-0-inward", start: ["back", 0, 0], steps: "ESESW" },
      { id: "l3-back-right-1", start: ["back", 5, 3], steps: "EEESWWWSEEE" },
      {
        id: "l3-back-left-1-inward",
        start: ["back", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l3-back-east-line", start: ["back", 1, 6], steps: "EEEEEEE" },
      { id: "l3-right-right-0", start: ["right", 7, 0], steps: "WSESE" },
      { id: "l3-right-left-0-inward", start: ["right", 0, 0], steps: "ESESE" },
      { id: "l3-right-right-1", start: ["right", 5, 3], steps: "EEESWWWSEEE" },
      {
        id: "l3-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l3-right-east-line", start: ["right", 1, 6], steps: "EEEEEEE" },
      {
        id: "l3-left-left-0-inward",
        start: ["left", 0, 2],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l3-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l3-left-west-line", start: ["left", 3, 6], steps: "WWW" },
      { id: "l3-top-left-0-inward", start: ["top", 0, 0], steps: "ESESW" },
      {
        id: "l3-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l3-top-west-line", start: ["top", 3, 6], steps: "WWW" },
      {
        id: "l3-bottom-right-1",
        start: ["bottom", 5, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l3-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l3-bottom-east-line", start: ["bottom", 1, 6], steps: "EEEEEEE" },
      { id: "l3-left-hook-fill-100", start: ["left", 6, 3], steps: "NWNWN" },
      { id: "l3-top-hook-fill-124", start: ["top", 5, 3], steps: "NWNWN" },
      { id: "l3-top-hook-fill-129", start: ["top", 4, 5], steps: "SESES" },
      { id: "l3-front-edge-fill-179", start: ["front", 5, 2], steps: "EEE" },
      { id: "l3-front-edge-fill-184", start: ["front", 4, 3], steps: "NNN" },
      { id: "l3-front-edge-fill-198", start: ["front", 3, 7], steps: "WWW" },
      { id: "l3-front-edge-fill-199", start: ["front", 5, 7], steps: "EEE" },
      { id: "l3-back-edge-fill-220", start: ["back", 4, 3], steps: "NNN" },
      { id: "l3-back-edge-fill-238", start: ["back", 3, 8], steps: "WWW" },
      { id: "l3-back-edge-fill-239", start: ["back", 5, 8], steps: "EEE" },
    ],
  },
  {
    id: 4,
    title: "Cube 4",
    gridSize: 10,
    lives: 4,
    routes: [
      { id: "l4-bottom-three-cell-line", start: ["bottom", 7, 9], steps: "EE" },
      { id: "l4-top-two-cell-line", start: ["top", 1, 9], steps: "W" },
      { id: "l4-top-wrap-west-8", start: ["top", 1, 8], steps: "WWSSSSSSSSS" },
      {
        id: "l4-front-wrap-north-8",
        start: ["front", 8, 1],
        steps: "NNNNNNNNNNN",
      },
      {
        id: "l4-right-wrap-east-8",
        start: ["right", 8, 8],
        steps: "EEEEEEEEEEE",
      },
      {
        id: "l4-left-wrap-south-7",
        start: ["left", 7, 8],
        steps: "SSEEEEEEEEE",
      },
      { id: "l4-front-left-0-inward", start: ["front", 0, 0], steps: "ESESW" },
      { id: "l4-front-right-1", start: ["front", 6, 3], steps: "EEESWWWSEEE" },
      {
        id: "l4-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l4-front-right-2", start: ["front", 6, 6], steps: "EEESWWWSEEE" },
      {
        id: "l4-front-left-2-inward",
        start: ["front", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l4-front-winder-4",
        start: ["front", 4, 0],
        steps: "SSESSWSSESSWS",
      },
      { id: "l4-front-west-line", start: ["front", 3, 9], steps: "WWW" },
      { id: "l4-back-right-0", start: ["back", 8, 0], steps: "WSESE" },
      { id: "l4-back-left-0-inward", start: ["back", 0, 0], steps: "ESESE" },
      { id: "l4-back-right-1", start: ["back", 6, 3], steps: "EEESWWWSEEE" },
      {
        id: "l4-back-left-1-inward",
        start: ["back", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l4-back-east-line", start: ["back", 2, 9], steps: "EEEEEEE" },
      { id: "l4-right-right-0", start: ["right", 6, 0], steps: "EEESWWWSEEE" },
      {
        id: "l4-right-left-0-inward",
        start: ["right", 0, 2],
        steps: "EEENWWWNEEE",
      },
      { id: "l4-right-right-1", start: ["right", 6, 3], steps: "EEESWWWSEEE" },
      {
        id: "l4-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l4-right-left-2-inward",
        start: ["right", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l4-right-winder-4",
        start: ["right", 4, 0],
        steps: "SSESSWSSESSWS",
      },
      { id: "l4-right-west-line", start: ["right", 3, 9], steps: "WWW" },
      { id: "l4-left-left-0-inward", start: ["left", 0, 0], steps: "ESESW" },
      {
        id: "l4-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l4-left-left-2-inward",
        start: ["left", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l4-left-winder-4", start: ["left", 4, 0], steps: "SSESSWSSESSWS" },
      { id: "l4-left-west-line", start: ["left", 3, 9], steps: "WWW" },
      { id: "l4-top-left-0-inward", start: ["top", 0, 0], steps: "ESESE" },
      {
        id: "l4-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l4-top-winder-4", start: ["top", 4, 0], steps: "SSESSWSSESSWS" },
      {
        id: "l4-bottom-right-1",
        start: ["bottom", 6, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l4-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l4-bottom-right-2",
        start: ["bottom", 6, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l4-bottom-left-2-inward",
        start: ["bottom", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l4-bottom-west-line", start: ["bottom", 3, 9], steps: "WWW" },
      { id: "l4-back-hook-fill-44", start: ["back", 5, 3], steps: "NWNWN" },
      { id: "l4-left-hook-fill-116", start: ["left", 7, 3], steps: "NWNWN" },
      { id: "l4-top-hook-fill-133", start: ["top", 1, 6], steps: "SESES" },
      { id: "l4-top-hook-fill-148", start: ["top", 7, 3], steps: "NWNWN" },
      { id: "l4-front-edge-fill-203", start: ["front", 6, 2], steps: "EEE" },
      { id: "l4-front-edge-fill-231", start: ["front", 6, 9], steps: "EEE" },
      { id: "l4-back-edge-fill-258", start: ["back", 3, 6], steps: "WWW" },
      { id: "l4-back-edge-fill-259", start: ["back", 6, 6], steps: "EEE" },
      { id: "l4-back-edge-fill-262", start: ["back", 3, 7], steps: "WWW" },
      { id: "l4-back-edge-fill-263", start: ["back", 6, 7], steps: "EEE" },
      { id: "l4-right-edge-fill-297", start: ["right", 6, 6], steps: "SSS" },
      { id: "l4-right-edge-fill-301", start: ["right", 7, 6], steps: "SSS" },
      { id: "l4-left-edge-fill-337", start: ["left", 6, 6], steps: "SSS" },
      { id: "l4-left-edge-fill-348", start: ["left", 9, 3], steps: "NNN" },
      { id: "l4-left-edge-fill-349", start: ["left", 9, 6], steps: "SSS" },
      { id: "l4-top-edge-fill-377", start: ["top", 6, 6], steps: "SSS" },
    ],
  },
  {
    id: 5,
    title: "Cube 5",
    gridSize: 11,
    lives: 4,
    routes: [
      { id: "l5-front-chain-a", start: ["front", 0, 10], steps: "E" },
      { id: "l5-front-chain-b", start: ["front", 2, 10], steps: "E" },
      { id: "l5-front-chain-c", start: ["front", 4, 10], steps: "E" },
      {
        id: "l5-top-wrap-west-9",
        start: ["top", 1, 9],
        steps: "WWSSSSSSSSSSSEEEEEEEEEE",
      },
      {
        id: "l5-front-wrap-north-9",
        start: ["front", 9, 1],
        steps: "NNNNNNNNNNNNNSSSSSSSSSS",
      },
      {
        id: "l5-left-wrap-south-8",
        start: ["left", 8, 9],
        steps: "SSEEEEEEEEEE",
      },
      { id: "l5-front-left-0-inward", start: ["front", 0, 0], steps: "ESESE" },
      { id: "l5-front-right-1", start: ["front", 7, 3], steps: "EEESWWWSEEE" },
      {
        id: "l5-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l5-front-right-2", start: ["front", 7, 6], steps: "EEESWWWSEEE" },
      {
        id: "l5-front-left-2-inward",
        start: ["front", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l5-front-east-line", start: ["front", 3, 9], steps: "EEEEEEE" },
      { id: "l5-back-right-0", start: ["back", 7, 0], steps: "EEESWWWSEEE" },
      { id: "l5-back-right-1", start: ["back", 7, 3], steps: "EEESWWWSEEE" },
      { id: "l5-back-right-2", start: ["back", 7, 6], steps: "EEESWWWSEEE" },
      {
        id: "l5-back-winder-4",
        start: ["back", 4, 0],
        steps: "SESWSESWSESWSESWSES",
      },
      { id: "l5-right-right-0", start: ["right", 7, 0], steps: "ESESE" },
      { id: "l5-right-left-0-inward", start: ["right", 0, 0], steps: "ESESW" },
      { id: "l5-right-right-1", start: ["right", 7, 3], steps: "EEESWWWSEEE" },
      {
        id: "l5-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l5-right-right-2", start: ["right", 7, 6], steps: "EEESWWWSEEE" },
      {
        id: "l5-right-left-2-inward",
        start: ["right", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l5-right-winder-4",
        start: ["right", 4, 0],
        steps: "SESWSESWSESWSESWSES",
      },
      { id: "l5-right-west-line", start: ["right", 3, 9], steps: "WWW" },
      { id: "l5-left-left-0-inward", start: ["left", 0, 0], steps: "ESESE" },
      {
        id: "l5-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l5-left-left-2-inward",
        start: ["left", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l5-left-winder-4",
        start: ["left", 4, 0],
        steps: "SESWSESWSESWSESWSES",
      },
      { id: "l5-left-west-line", start: ["left", 3, 9], steps: "WWW" },
      {
        id: "l5-top-left-0-inward",
        start: ["top", 0, 2],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l5-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l5-top-left-2-inward",
        start: ["top", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l5-top-winder-4",
        start: ["top", 4, 0],
        steps: "SESWSESWSESWSESWSES",
      },
      {
        id: "l5-bottom-right-1",
        start: ["bottom", 7, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l5-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l5-bottom-right-2",
        start: ["bottom", 7, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l5-bottom-left-2-inward",
        start: ["bottom", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l5-bottom-east-line", start: ["bottom", 3, 9], steps: "EEEEEEE" },
      { id: "l5-front-hook-fill-12", start: ["front", 5, 3], steps: "NWNWN" },
      { id: "l5-left-hook-fill-132", start: ["left", 8, 3], steps: "NWNWN" },
      { id: "l5-top-hook-fill-168", start: ["top", 8, 3], steps: "NWNWN" },
      { id: "l5-top-hook-fill-169", start: ["top", 6, 7], steps: "SESES" },
      { id: "l5-front-edge-fill-227", start: ["front", 7, 2], steps: "EEE" },
      { id: "l5-front-edge-fill-240", start: ["front", 6, 3], steps: "NNN" },
      { id: "l5-front-edge-fill-259", start: ["front", 7, 10], steps: "EEE" },
      { id: "l5-back-edge-fill-260", start: ["back", 0, 3], steps: "NNN" },
      { id: "l5-back-edge-fill-261", start: ["back", 0, 7], steps: "SSS" },
      { id: "l5-back-edge-fill-268", start: ["back", 2, 3], steps: "NNN" },
      { id: "l5-back-edge-fill-269", start: ["back", 2, 7], steps: "SSS" },
      { id: "l5-back-edge-fill-272", start: ["back", 3, 3], steps: "NNN" },
      { id: "l5-back-edge-fill-273", start: ["back", 3, 7], steps: "SSS" },
      { id: "l5-back-edge-fill-284", start: ["back", 6, 3], steps: "NNN" },
      { id: "l5-back-edge-fill-285", start: ["back", 6, 7], steps: "SSS" },
      { id: "l5-back-edge-fill-299", start: ["back", 7, 9], steps: "EEE" },
      { id: "l5-back-edge-fill-303", start: ["back", 7, 10], steps: "EEE" },
      { id: "l5-right-edge-fill-328", start: ["right", 6, 3], steps: "NNN" },
      { id: "l5-right-edge-fill-329", start: ["right", 6, 7], steps: "SSS" },
      { id: "l5-right-edge-fill-343", start: ["right", 7, 9], steps: "EEE" },
      { id: "l5-right-edge-fill-346", start: ["right", 3, 10], steps: "WWW" },
      { id: "l5-right-edge-fill-347", start: ["right", 7, 10], steps: "EEE" },
      { id: "l5-left-edge-fill-373", start: ["left", 6, 7], steps: "SSS" },
      { id: "l5-left-edge-fill-377", start: ["left", 7, 7], steps: "SSS" },
      { id: "l5-left-edge-fill-388", start: ["left", 10, 3], steps: "NNN" },
      { id: "l5-left-edge-fill-389", start: ["left", 10, 7], steps: "SSS" },
      { id: "l5-left-edge-fill-390", start: ["left", 3, 10], steps: "WWW" },
      { id: "l5-top-edge-fill-432", start: ["top", 10, 3], steps: "NNN" },
    ],
  },
  {
    id: 6,
    title: "Cube 6",
    gridSize: 12,
    lives: 4,
    routes: [
      { id: "l6-front-chain-a", start: ["front", 0, 11], steps: "E" },
      { id: "l6-front-chain-b", start: ["front", 2, 11], steps: "E" },
      { id: "l6-front-chain-c", start: ["front", 4, 11], steps: "E" },
      {
        id: "l6-top-wrap-west-10",
        start: ["top", 1, 10],
        steps: "WWSSSSSSSSSSSSEEEEEEEEEEE",
      },
      {
        id: "l6-front-wrap-north-10",
        start: ["front", 10, 1],
        steps: "NNNNNNNNNNNNNNSSSSSSSSSSS",
      },
      {
        id: "l6-left-wrap-south-9",
        start: ["left", 9, 10],
        steps: "SSEEEEEEEEEEE",
      },
      {
        id: "l6-front-left-0-inward",
        start: ["front", 0, 2],
        steps: "EEENWWWNEEE",
      },
      { id: "l6-front-right-1", start: ["front", 8, 3], steps: "EEESWWWSEEE" },
      {
        id: "l6-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l6-front-right-2", start: ["front", 8, 6], steps: "EEESWWWSEEE" },
      {
        id: "l6-front-left-2-inward",
        start: ["front", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l6-front-winder-6",
        start: ["front", 6, 0],
        steps: "SSESSWSSESSWSSES",
      },
      { id: "l6-front-west-line", start: ["front", 3, 9], steps: "WWW" },
      { id: "l6-back-right-0", start: ["back", 8, 0], steps: "ESESE" },
      { id: "l6-back-right-1", start: ["back", 8, 3], steps: "EEESWWWSEEE" },
      { id: "l6-back-right-2", start: ["back", 8, 6], steps: "EEESWWWSEEE" },
      {
        id: "l6-back-winder-4",
        start: ["back", 4, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      {
        id: "l6-back-winder-6",
        start: ["back", 6, 0],
        steps: "SSESSWSSESSWSSES",
      },
      { id: "l6-right-right-0", start: ["right", 10, 0], steps: "WSESE" },
      { id: "l6-right-left-0-inward", start: ["right", 0, 0], steps: "ESESE" },
      { id: "l6-right-right-1", start: ["right", 8, 3], steps: "EEESWWWSEEE" },
      {
        id: "l6-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l6-right-right-2", start: ["right", 8, 6], steps: "EEESWWWSEEE" },
      {
        id: "l6-right-left-2-inward",
        start: ["right", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l6-right-winder-4",
        start: ["right", 4, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      {
        id: "l6-right-winder-6",
        start: ["right", 6, 0],
        steps: "SSESSWSSESSWSSES",
      },
      { id: "l6-right-west-line", start: ["right", 3, 9], steps: "WWW" },
      {
        id: "l6-left-left-0-inward",
        start: ["left", 0, 2],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l6-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l6-left-left-2-inward",
        start: ["left", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l6-left-winder-4",
        start: ["left", 4, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      {
        id: "l6-left-winder-6",
        start: ["left", 6, 0],
        steps: "SSESSWSSESSWSSES",
      },
      { id: "l6-left-west-line", start: ["left", 3, 9], steps: "WWW" },
      { id: "l6-top-left-0-inward", start: ["top", 0, 0], steps: "ESESW" },
      {
        id: "l6-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l6-top-left-2-inward",
        start: ["top", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l6-top-winder-4",
        start: ["top", 4, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      {
        id: "l6-top-winder-6",
        start: ["top", 6, 0],
        steps: "SSESSWSSESSWSSES",
      },
      { id: "l6-top-west-line", start: ["top", 3, 9], steps: "WWW" },
      {
        id: "l6-bottom-right-1",
        start: ["bottom", 8, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l6-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l6-bottom-right-2",
        start: ["bottom", 8, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l6-bottom-left-2-inward",
        start: ["bottom", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l6-bottom-east-line", start: ["bottom", 4, 9], steps: "EEEEEEE" },
      { id: "l6-bottom-west-line", start: ["bottom", 3, 9], steps: "WWW" },
      { id: "l6-front-hook-fill-39", start: ["front", 8, 9], steps: "ESESE" },
      { id: "l6-back-hook-fill-79", start: ["back", 8, 9], steps: "ESESE" },
      { id: "l6-right-hook-fill-119", start: ["right", 8, 9], steps: "ESESE" },
      { id: "l6-left-hook-fill-148", start: ["left", 9, 3], steps: "NWNWN" },
      { id: "l6-top-hook-fill-188", start: ["top", 9, 3], steps: "NWNWN" },
      { id: "l6-front-edge-fill-251", start: ["front", 8, 2], steps: "EEE" },
      { id: "l6-front-edge-fill-256", start: ["front", 4, 3], steps: "NNN" },
      { id: "l6-front-edge-fill-260", start: ["front", 5, 3], steps: "NNN" },
      { id: "l6-front-edge-fill-282", start: ["front", 3, 10], steps: "WWW" },
      { id: "l6-back-edge-fill-288", start: ["back", 0, 3], steps: "NNN" },
      { id: "l6-back-edge-fill-289", start: ["back", 0, 8], steps: "SSS" },
      { id: "l6-back-edge-fill-296", start: ["back", 2, 3], steps: "NNN" },
      { id: "l6-back-edge-fill-297", start: ["back", 2, 8], steps: "SSS" },
      { id: "l6-back-edge-fill-300", start: ["back", 3, 3], steps: "NNN" },
      { id: "l6-back-edge-fill-301", start: ["back", 3, 8], steps: "SSS" },
      { id: "l6-right-edge-fill-378", start: ["right", 3, 10], steps: "WWW" },
      { id: "l6-right-edge-fill-382", start: ["right", 3, 11], steps: "WWW" },
      { id: "l6-left-edge-fill-417", start: ["left", 8, 8], steps: "SSS" },
      { id: "l6-left-edge-fill-426", start: ["left", 3, 10], steps: "WWW" },
      { id: "l6-left-edge-fill-428", start: ["left", 11, 3], steps: "NNN" },
      { id: "l6-left-edge-fill-429", start: ["left", 11, 8], steps: "SSS" },
      { id: "l6-left-edge-fill-430", start: ["left", 3, 11], steps: "WWW" },
      { id: "l6-top-edge-fill-465", start: ["top", 8, 8], steps: "SSS" },
      { id: "l6-top-edge-fill-469", start: ["top", 9, 8], steps: "SSS" },
      { id: "l6-top-edge-fill-476", start: ["top", 11, 3], steps: "NNN" },
      { id: "l6-top-edge-fill-477", start: ["top", 11, 8], steps: "SSS" },
      { id: "l6-top-edge-fill-478", start: ["top", 3, 11], steps: "WWW" },
      { id: "l6-bottom-edge-fill-482", start: ["bottom", 3, 0], steps: "WWW" },
      { id: "l6-bottom-edge-fill-483", start: ["bottom", 8, 0], steps: "EEE" },
      { id: "l6-bottom-edge-fill-522", start: ["bottom", 3, 10], steps: "WWW" },
      { id: "l6-bottom-edge-fill-523", start: ["bottom", 8, 10], steps: "EEE" },
      { id: "l6-bottom-edge-fill-526", start: ["bottom", 3, 11], steps: "WWW" },
      { id: "l6-bottom-edge-fill-527", start: ["bottom", 8, 11], steps: "EEE" },
    ],
  },
  {
    id: 7,
    title: "Cube 7",
    gridSize: 12,
    lives: 3,
    routes: [
      { id: "l7-front-chain-a", start: ["front", 0, 11], steps: "E" },
      { id: "l7-front-chain-b", start: ["front", 2, 11], steps: "E" },
      { id: "l7-front-chain-c", start: ["front", 4, 11], steps: "E" },
      { id: "l7-top-chain-a", start: ["top", 0, 11], steps: "E" },
      { id: "l7-top-chain-b", start: ["top", 2, 11], steps: "E" },
      { id: "l7-top-chain-c", start: ["top", 4, 11], steps: "E" },
      { id: "l7-left-chain-a", start: ["left", 0, 11], steps: "E" },
      { id: "l7-left-chain-b", start: ["left", 2, 11], steps: "E" },
      { id: "l7-left-chain-c", start: ["left", 4, 11], steps: "E" },
      {
        id: "l7-top-wrap-west-10",
        start: ["top", 1, 10],
        steps: "WWSSSSSSSSSSSSEEEEEEEEEEE",
      },
      {
        id: "l7-front-wrap-north-10",
        start: ["front", 10, 1],
        steps: "NNNNNNNNNNNNNNSSSSSSSSSSS",
      },
      {
        id: "l7-left-wrap-south-9",
        start: ["left", 9, 10],
        steps: "SSEEEEEEEEEEE",
      },
      { id: "l7-front-left-0-inward", start: ["front", 0, 0], steps: "ESESW" },
      { id: "l7-front-right-1", start: ["front", 8, 3], steps: "EEESWWWSEEE" },
      {
        id: "l7-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l7-front-right-2", start: ["front", 8, 6], steps: "EEESWWWSEEE" },
      {
        id: "l7-front-left-2-inward",
        start: ["front", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l7-front-winder-6",
        start: ["front", 6, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      { id: "l7-front-west-line", start: ["front", 3, 9], steps: "WWW" },
      { id: "l7-back-right-0", start: ["back", 10, 0], steps: "WSESE" },
      { id: "l7-back-right-1", start: ["back", 8, 3], steps: "EEESWWWSEEE" },
      { id: "l7-back-right-2", start: ["back", 8, 6], steps: "EEESWWWSEEE" },
      {
        id: "l7-back-winder-4",
        start: ["back", 4, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      {
        id: "l7-back-winder-6",
        start: ["back", 6, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      { id: "l7-right-right-0", start: ["right", 8, 0], steps: "EEESWWWSEEE" },
      {
        id: "l7-right-left-0-inward",
        start: ["right", 0, 2],
        steps: "EEENWWWNEEE",
      },
      { id: "l7-right-right-1", start: ["right", 8, 3], steps: "EEESWWWSEEE" },
      {
        id: "l7-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l7-right-right-2", start: ["right", 8, 6], steps: "EEESWWWSEEE" },
      {
        id: "l7-right-left-2-inward",
        start: ["right", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l7-right-winder-4",
        start: ["right", 4, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      {
        id: "l7-right-winder-6",
        start: ["right", 6, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      { id: "l7-right-west-line", start: ["right", 3, 9], steps: "WWW" },
      { id: "l7-left-left-0-inward", start: ["left", 0, 0], steps: "ESESW" },
      {
        id: "l7-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l7-left-left-2-inward",
        start: ["left", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l7-left-winder-6",
        start: ["left", 6, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      { id: "l7-left-west-line", start: ["left", 3, 9], steps: "WWW" },
      { id: "l7-top-left-0-inward", start: ["top", 0, 0], steps: "ESESE" },
      {
        id: "l7-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l7-top-left-2-inward",
        start: ["top", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l7-top-winder-6",
        start: ["top", 6, 0],
        steps: "SESWSESWSESWSESWSESWS",
      },
      { id: "l7-top-west-line", start: ["top", 3, 9], steps: "WWW" },
      {
        id: "l7-bottom-right-1",
        start: ["bottom", 8, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l7-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l7-bottom-right-2",
        start: ["bottom", 8, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l7-bottom-left-2-inward",
        start: ["bottom", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l7-bottom-east-line", start: ["bottom", 4, 9], steps: "EEEEEEE" },
      { id: "l7-bottom-west-line", start: ["bottom", 3, 9], steps: "WWW" },
      { id: "l7-front-hook-fill-12", start: ["front", 5, 3], steps: "NWNWN" },
      { id: "l7-front-hook-fill-39", start: ["front", 8, 9], steps: "ESESE" },
      { id: "l7-back-hook-fill-79", start: ["back", 8, 9], steps: "ESESE" },
      { id: "l7-right-hook-fill-119", start: ["right", 8, 9], steps: "ESESE" },
      { id: "l7-left-hook-fill-132", start: ["left", 5, 3], steps: "NWNWN" },
      { id: "l7-top-hook-fill-172", start: ["top", 5, 3], steps: "NWNWN" },
      { id: "l7-front-edge-fill-251", start: ["front", 8, 2], steps: "EEE" },
      { id: "l7-front-edge-fill-282", start: ["front", 3, 10], steps: "WWW" },
      { id: "l7-back-edge-fill-288", start: ["back", 0, 3], steps: "NNN" },
      { id: "l7-back-edge-fill-289", start: ["back", 0, 8], steps: "SSS" },
      { id: "l7-back-edge-fill-296", start: ["back", 2, 3], steps: "NNN" },
      { id: "l7-back-edge-fill-297", start: ["back", 2, 8], steps: "SSS" },
      { id: "l7-back-edge-fill-300", start: ["back", 3, 3], steps: "NNN" },
      { id: "l7-back-edge-fill-301", start: ["back", 3, 8], steps: "SSS" },
      { id: "l7-right-edge-fill-378", start: ["right", 3, 10], steps: "WWW" },
      { id: "l7-right-edge-fill-382", start: ["right", 3, 11], steps: "WWW" },
      { id: "l7-left-edge-fill-416", start: ["left", 8, 3], steps: "NNN" },
      { id: "l7-left-edge-fill-417", start: ["left", 8, 8], steps: "SSS" },
      { id: "l7-left-edge-fill-420", start: ["left", 9, 3], steps: "NNN" },
      { id: "l7-left-edge-fill-426", start: ["left", 3, 10], steps: "WWW" },
      { id: "l7-left-edge-fill-428", start: ["left", 11, 3], steps: "NNN" },
      { id: "l7-left-edge-fill-429", start: ["left", 11, 8], steps: "SSS" },
      { id: "l7-top-edge-fill-464", start: ["top", 8, 3], steps: "NNN" },
      { id: "l7-top-edge-fill-465", start: ["top", 8, 8], steps: "SSS" },
      { id: "l7-top-edge-fill-468", start: ["top", 9, 3], steps: "NNN" },
      { id: "l7-top-edge-fill-469", start: ["top", 9, 8], steps: "SSS" },
      { id: "l7-top-edge-fill-476", start: ["top", 11, 3], steps: "NNN" },
      { id: "l7-top-edge-fill-477", start: ["top", 11, 8], steps: "SSS" },
      { id: "l7-bottom-edge-fill-482", start: ["bottom", 3, 0], steps: "WWW" },
      { id: "l7-bottom-edge-fill-483", start: ["bottom", 8, 0], steps: "EEE" },
      { id: "l7-bottom-edge-fill-522", start: ["bottom", 3, 10], steps: "WWW" },
      { id: "l7-bottom-edge-fill-523", start: ["bottom", 8, 10], steps: "EEE" },
      { id: "l7-bottom-edge-fill-526", start: ["bottom", 3, 11], steps: "WWW" },
      { id: "l7-bottom-edge-fill-527", start: ["bottom", 8, 11], steps: "EEE" },
      { id: "l7-back-edge-fill-608", start: ["back", 8, 2], steps: "NN" },
    ],
  },
  {
    id: 8,
    title: "Cube 8",
    gridSize: 13,
    lives: 3,
    routes: [
      { id: "l8-front-chain-a", start: ["front", 0, 12], steps: "E" },
      { id: "l8-front-chain-b", start: ["front", 2, 12], steps: "E" },
      { id: "l8-front-chain-c", start: ["front", 4, 12], steps: "E" },
      { id: "l8-top-chain-a", start: ["top", 0, 12], steps: "E" },
      { id: "l8-top-chain-b", start: ["top", 2, 12], steps: "E" },
      { id: "l8-top-chain-c", start: ["top", 4, 12], steps: "E" },
      { id: "l8-left-chain-a", start: ["left", 0, 12], steps: "E" },
      { id: "l8-left-chain-b", start: ["left", 2, 12], steps: "E" },
      { id: "l8-left-chain-c", start: ["left", 4, 12], steps: "E" },
      {
        id: "l8-top-wrap-west-11",
        start: ["top", 1, 11],
        steps: "WWSSSSSSSSSSSSSEEEEEEEEEEEE",
      },
      {
        id: "l8-front-wrap-north-11",
        start: ["front", 11, 1],
        steps: "NNNNNNNNNNNNNNNSSSSSSSSSSSS",
      },
      {
        id: "l8-left-wrap-south-10",
        start: ["left", 10, 11],
        steps: "SSEEEEEEEEEEEE",
      },
      { id: "l8-front-left-0-inward", start: ["front", 0, 0], steps: "ESESE" },
      { id: "l8-front-right-1", start: ["front", 9, 3], steps: "EEESWWWSEEE" },
      {
        id: "l8-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l8-front-right-2", start: ["front", 9, 6], steps: "EEESWWWSEEE" },
      {
        id: "l8-front-left-2-inward",
        start: ["front", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l8-front-right-3", start: ["front", 9, 9], steps: "EEESWWWSEEE" },
      {
        id: "l8-front-left-3-inward",
        start: ["front", 0, 11],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l8-front-winder-6",
        start: ["front", 6, 0],
        steps: "SESWSESWSESWSESWSESWSES",
      },
      { id: "l8-back-right-0", start: ["back", 9, 0], steps: "EEESWWWSEEE" },
      { id: "l8-back-right-1", start: ["back", 9, 3], steps: "EEESWWWSEEE" },
      { id: "l8-back-right-2", start: ["back", 9, 6], steps: "EEESWWWSEEE" },
      { id: "l8-back-right-3", start: ["back", 9, 9], steps: "EEESWWWSEEE" },
      {
        id: "l8-back-winder-4",
        start: ["back", 4, 0],
        steps: "SSESSWSSESSWSSESS",
      },
      {
        id: "l8-back-winder-6",
        start: ["back", 6, 0],
        steps: "SESWSESWSESWSESWSESWSES",
      },
      { id: "l8-right-right-0", start: ["right", 9, 0], steps: "ESESE" },
      { id: "l8-right-left-0-inward", start: ["right", 0, 0], steps: "ESESW" },
      { id: "l8-right-right-1", start: ["right", 9, 3], steps: "EEESWWWSEEE" },
      {
        id: "l8-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l8-right-right-2", start: ["right", 9, 6], steps: "EEESWWWSEEE" },
      {
        id: "l8-right-left-2-inward",
        start: ["right", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l8-right-right-3", start: ["right", 9, 9], steps: "EEESWWWSEEE" },
      { id: "l8-right-left-3", start: ["right", 3, 9], steps: "WWWSEEESWWW" },
      {
        id: "l8-right-winder-4",
        start: ["right", 4, 0],
        steps: "SSESSWSSESSWSSESS",
      },
      {
        id: "l8-right-winder-6",
        start: ["right", 6, 0],
        steps: "SESWSESWSESWSESWSESWSES",
      },
      { id: "l8-right-west-line", start: ["right", 3, 12], steps: "WWW" },
      { id: "l8-left-left-0-inward", start: ["left", 0, 0], steps: "ESESE" },
      {
        id: "l8-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l8-left-left-2-inward",
        start: ["left", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l8-left-left-3", start: ["left", 3, 9], steps: "WWWSEEESWWW" },
      {
        id: "l8-left-winder-6",
        start: ["left", 6, 0],
        steps: "SESWSESWSESWSESWSESWSES",
      },
      {
        id: "l8-top-left-0-inward",
        start: ["top", 0, 2],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l8-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l8-top-left-2-inward",
        start: ["top", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l8-top-winder-6",
        start: ["top", 6, 0],
        steps: "SESWSESWSESWSESWSESWSES",
      },
      {
        id: "l8-bottom-right-1",
        start: ["bottom", 9, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l8-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l8-bottom-right-2",
        start: ["bottom", 9, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l8-bottom-left-2-inward",
        start: ["bottom", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l8-bottom-right-3",
        start: ["bottom", 9, 9],
        steps: "EEESWWWSEEE",
      },
      { id: "l8-bottom-left-3", start: ["bottom", 3, 9], steps: "WWWSEEESWWW" },
      { id: "l8-bottom-east-line", start: ["bottom", 5, 12], steps: "EEEEEEE" },
      { id: "l8-bottom-west-line", start: ["bottom", 3, 12], steps: "WWW" },
      { id: "l8-front-hook-fill-12", start: ["front", 5, 3], steps: "NWNWN" },
      { id: "l8-back-hook-fill-53", start: ["back", 2, 9], steps: "SESES" },
      { id: "l8-left-hook-fill-144", start: ["left", 5, 3], steps: "NWNWN" },
      { id: "l8-left-hook-fill-164", start: ["left", 10, 3], steps: "NWNWN" },
      { id: "l8-top-hook-fill-208", start: ["top", 10, 3], steps: "NWNWN" },
      { id: "l8-top-hook-fill-209", start: ["top", 8, 9], steps: "SESES" },
      { id: "l8-top-hook-fill-214", start: ["top", 3, 11], steps: "WNWNW" },
      { id: "l8-front-edge-fill-275", start: ["front", 9, 2], steps: "EEE" },
      { id: "l8-front-edge-fill-296", start: ["front", 8, 3], steps: "NNN" },
      { id: "l8-front-edge-fill-297", start: ["front", 8, 9], steps: "SSS" },
      { id: "l8-front-edge-fill-315", start: ["front", 9, 12], steps: "EEE" },
      { id: "l8-back-edge-fill-316", start: ["back", 0, 3], steps: "NNN" },
      { id: "l8-back-edge-fill-317", start: ["back", 0, 9], steps: "SSS" },
      { id: "l8-back-edge-fill-324", start: ["back", 2, 3], steps: "NNN" },
      { id: "l8-back-edge-fill-328", start: ["back", 3, 3], steps: "NNN" },
      { id: "l8-back-edge-fill-348", start: ["back", 8, 3], steps: "NNN" },
      { id: "l8-back-edge-fill-349", start: ["back", 8, 9], steps: "SSS" },
      { id: "l8-back-edge-fill-367", start: ["back", 9, 12], steps: "EEE" },
      { id: "l8-right-edge-fill-400", start: ["right", 8, 3], steps: "NNN" },
      { id: "l8-right-edge-fill-401", start: ["right", 8, 9], steps: "SSS" },
      { id: "l8-right-edge-fill-419", start: ["right", 9, 12], steps: "EEE" },
      { id: "l8-left-edge-fill-453", start: ["left", 8, 9], steps: "SSS" },
      { id: "l8-left-edge-fill-457", start: ["left", 9, 9], steps: "SSS" },
      { id: "l8-left-edge-fill-468", start: ["left", 12, 3], steps: "NNN" },
      { id: "l8-left-edge-fill-469", start: ["left", 12, 9], steps: "SSS" },
      { id: "l8-top-edge-fill-488", start: ["top", 4, 3], steps: "NNN" },
      { id: "l8-top-edge-fill-492", start: ["top", 5, 3], steps: "NNN" },
      { id: "l8-top-edge-fill-520", start: ["top", 12, 3], steps: "NNN" },
      { id: "l8-top-edge-fill-521", start: ["top", 12, 9], steps: "SSS" },
      { id: "l8-bottom-edge-fill-526", start: ["bottom", 3, 0], steps: "WWW" },
      { id: "l8-bottom-edge-fill-527", start: ["bottom", 9, 0], steps: "EEE" },
      { id: "l8-bottom-edge-fill-541", start: ["bottom", 4, 9], steps: "SSS" },
      { id: "l8-right-edge-fill-692", start: ["right", 3, 2], steps: "NN" },
      { id: "l8-front-edge-fill-898", start: ["front", 1, 2], steps: "W" },
      { id: "l8-front-edge-fill-908", start: ["front", 5, 1], steps: "N" },
      { id: "l8-front-edge-fill-924", start: ["front", 9, 1], steps: "N" },
    ],
  },
  {
    id: 9,
    title: "Cube 9",
    gridSize: 14,
    lives: 3,
    routes: [
      { id: "l9-front-chain-a", start: ["front", 0, 13], steps: "E" },
      { id: "l9-front-chain-b", start: ["front", 2, 13], steps: "E" },
      { id: "l9-front-chain-c", start: ["front", 4, 13], steps: "E" },
      { id: "l9-top-chain-a", start: ["top", 0, 13], steps: "E" },
      { id: "l9-top-chain-b", start: ["top", 2, 13], steps: "E" },
      { id: "l9-top-chain-c", start: ["top", 4, 13], steps: "E" },
      { id: "l9-left-chain-a", start: ["left", 0, 13], steps: "E" },
      { id: "l9-left-chain-b", start: ["left", 2, 13], steps: "E" },
      { id: "l9-left-chain-c", start: ["left", 4, 13], steps: "E" },
      {
        id: "l9-top-wrap-west-12",
        start: ["top", 1, 12],
        steps: "WWSSSSSSSSSSSSSSEEEEEEEEEEEEE",
      },
      {
        id: "l9-front-wrap-north-12",
        start: ["front", 12, 1],
        steps: "NNNNNNNNNNNNNNNNSSSSSSSSSSSSS",
      },
      {
        id: "l9-left-wrap-south-11",
        start: ["left", 11, 12],
        steps: "SSEEEEEEEEEEEEE",
      },
      {
        id: "l9-front-left-0-inward",
        start: ["front", 0, 2],
        steps: "EEENWWWNEEE",
      },
      { id: "l9-front-right-1", start: ["front", 10, 3], steps: "EEESWWWSEEE" },
      {
        id: "l9-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l9-front-right-2", start: ["front", 10, 6], steps: "EEESWWWSEEE" },
      {
        id: "l9-front-left-2-inward",
        start: ["front", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l9-front-right-3", start: ["front", 10, 9], steps: "EEESWWWSEEE" },
      {
        id: "l9-front-left-3-inward",
        start: ["front", 0, 11],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l9-front-winder-6",
        start: ["front", 6, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l9-front-winder-8",
        start: ["front", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      { id: "l9-front-west-line", start: ["front", 3, 12], steps: "WWW" },
      { id: "l9-back-right-0", start: ["back", 10, 0], steps: "ESESE" },
      { id: "l9-back-right-1", start: ["back", 10, 3], steps: "EEESWWWSEEE" },
      { id: "l9-back-right-2", start: ["back", 10, 6], steps: "EEESWWWSEEE" },
      { id: "l9-back-right-3", start: ["back", 10, 9], steps: "EEESWWWSEEE" },
      {
        id: "l9-back-winder-4",
        start: ["back", 4, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l9-back-winder-6",
        start: ["back", 6, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l9-back-winder-8",
        start: ["back", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      { id: "l9-right-right-0", start: ["right", 12, 0], steps: "WSESE" },
      { id: "l9-right-left-0-inward", start: ["right", 0, 0], steps: "ESESE" },
      { id: "l9-right-right-1", start: ["right", 10, 3], steps: "EEESWWWSEEE" },
      {
        id: "l9-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      { id: "l9-right-right-2", start: ["right", 10, 6], steps: "EEESWWWSEEE" },
      {
        id: "l9-right-left-2-inward",
        start: ["right", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l9-right-right-3", start: ["right", 10, 9], steps: "EEESWWWSEEE" },
      { id: "l9-right-left-3", start: ["right", 3, 9], steps: "WWWSEEESWWW" },
      {
        id: "l9-right-winder-4",
        start: ["right", 4, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l9-right-winder-6",
        start: ["right", 6, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l9-right-winder-8",
        start: ["right", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      { id: "l9-right-west-line", start: ["right", 3, 12], steps: "WWW" },
      {
        id: "l9-left-left-0-inward",
        start: ["left", 0, 2],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l9-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l9-left-left-2-inward",
        start: ["left", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l9-left-left-3", start: ["left", 3, 9], steps: "WWWSEEESWWW" },
      {
        id: "l9-left-winder-6",
        start: ["left", 6, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l9-left-winder-8",
        start: ["left", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      { id: "l9-left-west-line", start: ["left", 3, 12], steps: "WWW" },
      { id: "l9-top-left-0-inward", start: ["top", 0, 0], steps: "ESESW" },
      {
        id: "l9-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l9-top-left-2-inward",
        start: ["top", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l9-top-left-3", start: ["top", 3, 9], steps: "WWWSEEESWWW" },
      {
        id: "l9-top-winder-6",
        start: ["top", 6, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l9-top-winder-8",
        start: ["top", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l9-bottom-right-1",
        start: ["bottom", 10, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l9-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l9-bottom-right-2",
        start: ["bottom", 10, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l9-bottom-left-2-inward",
        start: ["bottom", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l9-bottom-right-3",
        start: ["bottom", 10, 9],
        steps: "EEESWWWSEEE",
      },
      { id: "l9-bottom-left-3", start: ["bottom", 3, 9], steps: "WWWSEEESWWW" },
      { id: "l9-bottom-east-line", start: ["bottom", 6, 12], steps: "EEEEEEE" },
      { id: "l9-bottom-west-line", start: ["bottom", 3, 12], steps: "WWW" },
      { id: "l9-top-hook-fill-204", start: ["top", 5, 3], steps: "NWNWN" },
      { id: "l9-front-edge-fill-299", start: ["front", 10, 2], steps: "EEE" },
      { id: "l9-front-edge-fill-304", start: ["front", 4, 3], steps: "NNN" },
      { id: "l9-front-edge-fill-308", start: ["front", 5, 3], steps: "NNN" },
      { id: "l9-front-edge-fill-339", start: ["front", 10, 12], steps: "EEE" },
      { id: "l9-front-edge-fill-343", start: ["front", 10, 13], steps: "EEE" },
      { id: "l9-back-edge-fill-344", start: ["back", 0, 3], steps: "NNN" },
      { id: "l9-back-edge-fill-345", start: ["back", 0, 10], steps: "SSS" },
      { id: "l9-back-edge-fill-352", start: ["back", 2, 3], steps: "NNN" },
      { id: "l9-back-edge-fill-353", start: ["back", 2, 10], steps: "SSS" },
      { id: "l9-back-edge-fill-356", start: ["back", 3, 3], steps: "NNN" },
      { id: "l9-back-edge-fill-357", start: ["back", 3, 10], steps: "SSS" },
      { id: "l9-back-edge-fill-395", start: ["back", 10, 12], steps: "EEE" },
      { id: "l9-back-edge-fill-399", start: ["back", 10, 13], steps: "EEE" },
      { id: "l9-right-edge-fill-451", start: ["right", 10, 12], steps: "EEE" },
      { id: "l9-right-edge-fill-454", start: ["right", 3, 13], steps: "WWW" },
      { id: "l9-right-edge-fill-455", start: ["right", 10, 13], steps: "EEE" },
      { id: "l9-left-edge-fill-472", start: ["left", 4, 3], steps: "NNN" },
      { id: "l9-left-edge-fill-476", start: ["left", 5, 3], steps: "NNN" },
      { id: "l9-left-edge-fill-496", start: ["left", 10, 3], steps: "NNN" },
      { id: "l9-left-edge-fill-497", start: ["left", 10, 10], steps: "SSS" },
      { id: "l9-left-edge-fill-500", start: ["left", 11, 3], steps: "NNN" },
      { id: "l9-left-edge-fill-508", start: ["left", 13, 3], steps: "NNN" },
      { id: "l9-left-edge-fill-509", start: ["left", 13, 10], steps: "SSS" },
      { id: "l9-top-edge-fill-552", start: ["top", 10, 3], steps: "NNN" },
      { id: "l9-top-edge-fill-553", start: ["top", 10, 10], steps: "SSS" },
      { id: "l9-top-edge-fill-556", start: ["top", 11, 3], steps: "NNN" },
      { id: "l9-top-edge-fill-557", start: ["top", 11, 10], steps: "SSS" },
    ],
  },
  {
    id: 10,
    title: "Cube 10",
    gridSize: 14,
    lives: 3,
    routes: [
      { id: "l10-front-chain-a", start: ["front", 0, 13], steps: "E" },
      { id: "l10-front-chain-b", start: ["front", 2, 13], steps: "E" },
      { id: "l10-front-chain-c", start: ["front", 4, 13], steps: "E" },
      { id: "l10-top-chain-a", start: ["top", 0, 13], steps: "E" },
      { id: "l10-top-chain-b", start: ["top", 2, 13], steps: "E" },
      { id: "l10-top-chain-c", start: ["top", 4, 13], steps: "E" },
      { id: "l10-left-chain-a", start: ["left", 0, 13], steps: "E" },
      { id: "l10-left-chain-b", start: ["left", 2, 13], steps: "E" },
      { id: "l10-left-chain-c", start: ["left", 4, 13], steps: "E" },
      {
        id: "l10-top-wrap-west-12",
        start: ["top", 1, 12],
        steps: "WWSSSSSSSSSSSSSSEEEEEEEEEEEEE",
      },
      {
        id: "l10-front-wrap-north-12",
        start: ["front", 12, 1],
        steps: "NNNNNNNNNNNNNNNNSSSSSSSSSSSSS",
      },
      {
        id: "l10-left-wrap-south-11",
        start: ["left", 11, 12],
        steps: "SSEEEEEEEEEEEEE",
      },
      { id: "l10-front-left-0-inward", start: ["front", 0, 0], steps: "ESESW" },
      {
        id: "l10-front-right-1",
        start: ["front", 10, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-front-left-1-inward",
        start: ["front", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-front-right-2",
        start: ["front", 10, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-front-left-2-inward",
        start: ["front", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-front-right-3",
        start: ["front", 10, 9],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-front-left-3-inward",
        start: ["front", 0, 11],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-front-winder-6",
        start: ["front", 6, 0],
        steps: "SSESSWSSESSWSSESSWS",
      },
      {
        id: "l10-front-winder-8",
        start: ["front", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      { id: "l10-front-west-line", start: ["front", 3, 12], steps: "WWW" },
      { id: "l10-back-right-0", start: ["back", 12, 0], steps: "WSESE" },
      { id: "l10-back-right-1", start: ["back", 10, 3], steps: "EEESWWWSEEE" },
      { id: "l10-back-right-2", start: ["back", 10, 6], steps: "EEESWWWSEEE" },
      { id: "l10-back-right-3", start: ["back", 10, 9], steps: "EEESWWWSEEE" },
      {
        id: "l10-back-winder-4",
        start: ["back", 4, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l10-back-winder-6",
        start: ["back", 6, 0],
        steps: "SSESSWSSESSWSSESSWS",
      },
      {
        id: "l10-back-winder-8",
        start: ["back", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l10-right-right-0",
        start: ["right", 10, 0],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-right-left-0-inward",
        start: ["right", 0, 2],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-right-right-1",
        start: ["right", 10, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-right-left-1-inward",
        start: ["right", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-right-right-2",
        start: ["right", 10, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-right-left-2-inward",
        start: ["right", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-right-right-3",
        start: ["right", 10, 9],
        steps: "EEESWWWSEEE",
      },
      { id: "l10-right-left-3", start: ["right", 3, 9], steps: "WWWSEEESWWW" },
      {
        id: "l10-right-winder-4",
        start: ["right", 4, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l10-right-winder-6",
        start: ["right", 6, 0],
        steps: "SSESSWSSESSWSSESSWS",
      },
      {
        id: "l10-right-winder-8",
        start: ["right", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      { id: "l10-right-west-line", start: ["right", 3, 12], steps: "WWW" },
      { id: "l10-left-left-0-inward", start: ["left", 0, 0], steps: "ESESW" },
      {
        id: "l10-left-left-1-inward",
        start: ["left", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-left-left-2-inward",
        start: ["left", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l10-left-left-3", start: ["left", 3, 9], steps: "WWWSEEESWWW" },
      {
        id: "l10-left-winder-6",
        start: ["left", 6, 0],
        steps: "SSESSWSSESSWSSESSWS",
      },
      {
        id: "l10-left-winder-8",
        start: ["left", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      { id: "l10-left-west-line", start: ["left", 3, 12], steps: "WWW" },
      { id: "l10-top-left-0-inward", start: ["top", 0, 0], steps: "ESESE" },
      {
        id: "l10-top-left-1-inward",
        start: ["top", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-top-left-2-inward",
        start: ["top", 0, 8],
        steps: "EEENWWWNEEE",
      },
      { id: "l10-top-left-3", start: ["top", 3, 9], steps: "WWWSEEESWWW" },
      {
        id: "l10-top-winder-6",
        start: ["top", 6, 0],
        steps: "SSESSWSSESSWSSESSWS",
      },
      {
        id: "l10-top-winder-8",
        start: ["top", 8, 0],
        steps: "SESWSESWSESWSESWSESWSESWS",
      },
      {
        id: "l10-bottom-right-1",
        start: ["bottom", 10, 3],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-bottom-left-1-inward",
        start: ["bottom", 0, 5],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-bottom-right-2",
        start: ["bottom", 10, 6],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-bottom-left-2-inward",
        start: ["bottom", 0, 8],
        steps: "EEENWWWNEEE",
      },
      {
        id: "l10-bottom-right-3",
        start: ["bottom", 10, 9],
        steps: "EEESWWWSEEE",
      },
      {
        id: "l10-bottom-left-3",
        start: ["bottom", 3, 9],
        steps: "WWWSEEESWWW",
      },
      {
        id: "l10-bottom-east-line",
        start: ["bottom", 6, 12],
        steps: "EEEEEEE",
      },
      { id: "l10-bottom-west-line", start: ["bottom", 3, 12], steps: "WWW" },
      { id: "l10-front-hook-fill-12", start: ["front", 5, 3], steps: "NWNWN" },
      { id: "l10-left-hook-fill-156", start: ["left", 5, 3], steps: "NWNWN" },
      { id: "l10-top-hook-fill-204", start: ["top", 5, 3], steps: "NWNWN" },
      { id: "l10-front-edge-fill-299", start: ["front", 10, 2], steps: "EEE" },
      { id: "l10-front-edge-fill-339", start: ["front", 10, 12], steps: "EEE" },
      { id: "l10-front-edge-fill-343", start: ["front", 10, 13], steps: "EEE" },
      { id: "l10-back-edge-fill-344", start: ["back", 0, 3], steps: "NNN" },
      { id: "l10-back-edge-fill-345", start: ["back", 0, 10], steps: "SSS" },
      { id: "l10-back-edge-fill-352", start: ["back", 2, 3], steps: "NNN" },
      { id: "l10-back-edge-fill-353", start: ["back", 2, 10], steps: "SSS" },
      { id: "l10-back-edge-fill-356", start: ["back", 3, 3], steps: "NNN" },
      { id: "l10-back-edge-fill-357", start: ["back", 3, 10], steps: "SSS" },
      { id: "l10-back-edge-fill-395", start: ["back", 10, 12], steps: "EEE" },
      { id: "l10-back-edge-fill-399", start: ["back", 10, 13], steps: "EEE" },
      { id: "l10-right-edge-fill-451", start: ["right", 10, 12], steps: "EEE" },
      { id: "l10-right-edge-fill-454", start: ["right", 3, 13], steps: "WWW" },
      { id: "l10-right-edge-fill-455", start: ["right", 10, 13], steps: "EEE" },
      { id: "l10-left-edge-fill-496", start: ["left", 10, 3], steps: "NNN" },
      { id: "l10-left-edge-fill-497", start: ["left", 10, 10], steps: "SSS" },
      { id: "l10-left-edge-fill-500", start: ["left", 11, 3], steps: "NNN" },
      { id: "l10-left-edge-fill-508", start: ["left", 13, 3], steps: "NNN" },
      { id: "l10-left-edge-fill-509", start: ["left", 13, 10], steps: "SSS" },
      { id: "l10-top-edge-fill-552", start: ["top", 10, 3], steps: "NNN" },
      { id: "l10-top-edge-fill-553", start: ["top", 10, 10], steps: "SSS" },
      { id: "l10-top-edge-fill-556", start: ["top", 11, 3], steps: "NNN" },
      { id: "l10-top-edge-fill-557", start: ["top", 11, 10], steps: "SSS" },
      { id: "l10-top-edge-fill-564", start: ["top", 13, 3], steps: "NNN" },
      { id: "l10-top-edge-fill-565", start: ["top", 13, 10], steps: "SSS" },
    ],
  },
];

/** Frozen authored routes. Runtime only decodes approved fixed steps; it never searches or places arrows. */
export const CAMPAIGN_LAYOUTS: readonly LevelDefinition[] = FROZEN_LAYOUTS.map(
  (layout) => ({
    id: layout.id,
    title: layout.title,
    gridSize: layout.gridSize,
    lives: layout.lives,
    arrows: layout.routes.map((route) => ({
      id: route.id,
      path: decodeRoute(route, layout.gridSize),
    })),
  }),
);
