import type { LevelDefinition } from "../core/types";
import { decodeRoute, type FrozenRoute } from "./route-codec";
export { decodeRoute, type FrozenRoute } from "./route-codec";

interface FrozenLayout {
  readonly id: number;
  readonly title: string;
  readonly gridSize: number;
  readonly lives: number;
  readonly routes: readonly FrozenRoute[];
}
const FROZEN_LAYOUTS: readonly FrozenLayout[] = [
  {
    id: 2,
    title: "Cube 2",
    gridSize: 8,
    lives: 5,
    routes: [
      { id: "l2-straight-2", start: ["front", 6, 0], steps: "E" },
      { id: "l2-straight-3", start: ["back", 5, 1], steps: "EE" },
      { id: "l2-straight-4", start: ["right", 4, 2], steps: "EEE" },
      { id: "l2-3", start: ["front", 5, 0], steps: "WSWWNNWSWWSSSE" },
      { id: "l2-4", start: ["front", 7, 2], steps: "EESWWWNW" },
      { id: "l2-5", start: ["back", 4, 2], steps: "EEESEEESW" },
      { id: "l2-6", start: ["front", 0, 1], steps: "ESW" },
      { id: "l2-7", start: ["back", 6, 3], steps: "WSESSS" },
      { id: "l2-8", start: ["bottom", 3, 0], steps: "SSWWSEES" },
      { id: "l2-9", start: ["top", 6, 1], steps: "WSESSEESSWSSW" },
      { id: "l2-10", start: ["back", 4, 3], steps: "WSES" },
      { id: "l2-11", start: ["right", 5, 7], steps: "WSNEWSWSS" },
      { id: "l2-12", start: ["left", 0, 2], steps: "EENWNEESS" },
      { id: "l2-13", start: ["left", 2, 5], steps: "WWWSEESWWSEE" },
      { id: "l2-14", start: ["right", 0, 7], steps: "WWWSSSSSSSWNN" },
      { id: "l2-15", start: ["back", 3, 0], steps: "ESWWWNENW" },
      { id: "l2-16", start: ["front", 3, 6], steps: "EENEEENW" },
      { id: "l2-17", start: ["bottom", 7, 7], steps: "NEEEESNNE" },
      { id: "l2-18", start: ["front", 3, 0], steps: "NNNENES" },
      { id: "l2-19", start: ["back", 0, 3], steps: "WSWWWSE" },
      { id: "l2-20", start: ["right", 4, 1], steps: "EENWWNN" },
      { id: "l2-21", start: ["bottom", 0, 1], steps: "ENNNNWWS" },
      { id: "l2-22", start: ["top", 3, 4], steps: "NWSW" },
      { id: "l2-23", start: ["back", 1, 5], steps: "NWSSWWWWWWNWSW" },
      { id: "l2-24", start: ["front", 6, 1], steps: "EEEENNWSEEW" },
      { id: "l2-25", start: ["left", 0, 1], steps: "NNSEESW" },
      { id: "l2-26", start: ["left", 6, 5], steps: "WSWSWNWSSNNNWE" },
      { id: "l2-27", start: ["left", 3, 5], steps: "NNEENEN" },
      { id: "l2-28", start: ["top", 2, 5], steps: "WWSWWSWN" },
      { id: "l2-29", start: ["front", 4, 5], steps: "NWSWSS" },
    ],
  },
  {
    id: 3,
    title: "Cube 3",
    gridSize: 9,
    lives: 5,
    routes: [
      { id: "l3-straight-2", start: ["front", 7, 0], steps: "E" },
      { id: "l3-straight-3", start: ["back", 6, 1], steps: "EE" },
      { id: "l3-straight-4", start: ["right", 5, 2], steps: "EEE" },
      { id: "l3-3", start: ["front", 7, 4], steps: "NNWWWNNENN" },
      { id: "l3-4", start: ["back", 1, 7], steps: "ENESEEEEENEE" },
      { id: "l3-5", start: ["top", 2, 3], steps: "SEESWSSESW" },
      { id: "l3-6", start: ["bottom", 8, 3], steps: "ENNENWNEE" },
      { id: "l3-7", start: ["top", 5, 2], steps: "NNESENEEE" },
      { id: "l3-8", start: ["front", 6, 8], steps: "WSWNWSS" },
      { id: "l3-9", start: ["back", 6, 0], steps: "EEESENESSE" },
      { id: "l3-10", start: ["bottom", 8, 8], steps: "WWSESNWWSWWW" },
      { id: "l3-11", start: ["left", 7, 7], steps: "SEEESSWSE" },
      { id: "l3-12", start: ["back", 2, 4], steps: "ESESEN" },
      { id: "l3-13", start: ["front", 3, 7], steps: "EENWWWNEN" },
      { id: "l3-14", start: ["left", 6, 2], steps: "NENNEENNWNW" },
      { id: "l3-15", start: ["right", 1, 4], steps: "NWWSESS" },
      { id: "l3-16", start: ["top", 2, 1], steps: "SESENN" },
      { id: "l3-17", start: ["bottom", 6, 4], steps: "NENEN" },
      { id: "l3-18", start: ["front", 5, 4], steps: "ENWWWNNWW" },
      { id: "l3-19", start: ["back", 4, 3], steps: "NWSWW" },
      { id: "l3-20", start: ["right", 7, 7], steps: "SSWWNENWWSWNW" },
      { id: "l3-21", start: ["right", 3, 1], steps: "SWSEEEEE" },
      { id: "l3-22", start: ["left", 8, 5], steps: "NNWNEENWN" },
      { id: "l3-23", start: ["bottom", 8, 4], steps: "ENENNESEEES" },
      { id: "l3-24", start: ["back", 1, 6], steps: "NNW" },
      { id: "l3-25", start: ["back", 4, 4], steps: "EN" },
      { id: "l3-26", start: ["bottom", 5, 2], steps: "SWWSWNWW" },
      { id: "l3-27", start: ["front", 7, 5], steps: "WSEESEENESSW" },
      { id: "l3-28", start: ["top", 7, 7], steps: "SWNNNNWNENESE" },
      { id: "l3-29", start: ["left", 2, 8], steps: "SENNWWEN" },
      { id: "l3-30", start: ["left", 4, 7], steps: "WWNENESENES" },
      { id: "l3-31", start: ["bottom", 7, 1], steps: "WNE" },
      { id: "l3-32", start: ["back", 3, 1], steps: "EENWNW" },
      { id: "l3-33", start: ["front", 5, 1], steps: "E" },
      { id: "l3-34", start: ["back", 1, 8], steps: "W" },
      { id: "l3-35", start: ["left", 3, 1], steps: "EESWSSWW" },
      { id: "l3-36", start: ["back", 0, 1], steps: "WWWWWNWWNSEW" },
      { id: "l3-37", start: ["left", 6, 7], steps: "S" },
      { id: "l3-38", start: ["top", 2, 0], steps: "WSSSWN" },
      { id: "l3-39", start: ["front", 6, 7], steps: "ES" },
      { id: "l3-40", start: ["front", 2, 3], steps: "NWSWSSESSW" },
      { id: "l3-41", start: ["back", 1, 1], steps: "NESSW" },
    ],
  },
  {
    id: 4,
    title: "Cube 4",
    gridSize: 10,
    lives: 4,
    routes: [
      { id: "l4-straight-2", start: ["front", 8, 0], steps: "E" },
      { id: "l4-straight-3", start: ["back", 7, 1], steps: "EE" },
      { id: "l4-straight-4", start: ["right", 6, 2], steps: "EEE" },
      { id: "l4-3", start: ["front", 0, 1], steps: "SESSWNWN" },
      { id: "l4-4", start: ["left", 3, 4], steps: "SEEEESWSEEESW" },
      { id: "l4-5", start: ["left", 9, 5], steps: "SESENNE" },
      { id: "l4-6", start: ["left", 5, 6], steps: "WSESSE" },
      { id: "l4-7", start: ["top", 6, 2], steps: "EENESSEWNWWSE" },
      { id: "l4-8", start: ["left", 2, 2], steps: "WWWSWS" },
      { id: "l4-9", start: ["right", 9, 6], steps: "ESESWSWWWWNEE" },
      { id: "l4-10", start: ["top", 6, 3], steps: "WWWSSESW" },
      { id: "l4-11", start: ["back", 0, 5], steps: "WWNWSSSWWSS" },
      { id: "l4-12", start: ["right", 2, 4], steps: "NNEESENNWWN" },
      { id: "l4-13", start: ["front", 6, 0], steps: "NNWWNEE" },
      { id: "l4-14", start: ["back", 6, 9], steps: "ENNNWWN" },
      { id: "l4-15", start: ["back", 1, 1], steps: "ESSSESES" },
      { id: "l4-16", start: ["bottom", 5, 8], steps: "WWWWSEEE" },
      { id: "l4-17", start: ["bottom", 3, 6], steps: "WNWWWNWWSS" },
      { id: "l4-18", start: ["right", 4, 0], steps: "NSWSEESW" },
      { id: "l4-19", start: ["bottom", 9, 9], steps: "NNNNNNEWSWS" },
      { id: "l4-20", start: ["front", 4, 3], steps: "ENWNWNW" },
      { id: "l4-21", start: ["front", 7, 7], steps: "SESWSWWNWSW" },
      { id: "l4-22", start: ["bottom", 6, 8], steps: "NENWNNWW" },
      { id: "l4-23", start: ["bottom", 5, 9], steps: "ESNES" },
      { id: "l4-24", start: ["front", 6, 9], steps: "NNNWSSW" },
      { id: "l4-25", start: ["bottom", 8, 0], steps: "SENNEN" },
      { id: "l4-26", start: ["bottom", 4, 6], steps: "SENNWWNNNWSSW" },
      { id: "l4-27", start: ["back", 0, 2], steps: "NNENWWNENWNE" },
      { id: "l4-28", start: ["right", 1, 0], steps: "NSESSWWWWNE" },
      { id: "l4-29", start: ["front", 2, 7], steps: "EENWNEE" },
      { id: "l4-30", start: ["front", 3, 9], steps: "NWSSWNNWS" },
      { id: "l4-31", start: ["right", 4, 9], steps: "NWNENENWWWW" },
      { id: "l4-32", start: ["front", 2, 1], steps: "WNWNEENN" },
      { id: "l4-33", start: ["left", 3, 2], steps: "ENNEENEENNW" },
      { id: "l4-34", start: ["top", 9, 0], steps: "EWSE" },
      { id: "l4-35", start: ["right", 0, 6], steps: "WSWNWNNWNEESE" },
      { id: "l4-36", start: ["top", 1, 1], steps: "WWENESENEN" },
      { id: "l4-37", start: ["top", 0, 3], steps: "WSWW" },
      { id: "l4-38", start: ["bottom", 0, 4], steps: "N" },
      { id: "l4-39", start: ["back", 9, 6], steps: "SESSSSWNE" },
      { id: "l4-40", start: ["bottom", 0, 8], steps: "WNNNNNNW" },
      { id: "l4-41", start: ["right", 8, 6], steps: "SE" },
      { id: "l4-42", start: ["front", 8, 1], steps: "E" },
      { id: "l4-43", start: ["top", 4, 4], steps: "EESWSEES" },
      { id: "l4-44", start: ["left", 5, 3], steps: "NESENENNNENW" },
      { id: "l4-45", start: ["bottom", 4, 3], steps: "EENENWWSWNWWW" },
      { id: "l4-46", start: ["bottom", 1, 3], steps: "NW" },
      { id: "l4-47", start: ["left", 6, 8], steps: "ES" },
      { id: "l4-48", start: ["top", 3, 0], steps: "W" },
      { id: "l4-49", start: ["back", 7, 0], steps: "E" },
      { id: "l4-50", start: ["bottom", 7, 3], steps: "SSESSS" },
      { id: "l4-51", start: ["right", 6, 1], steps: "EN" },
      { id: "l4-52", start: ["front", 7, 0], steps: "NNES" },
      { id: "l4-53", start: ["back", 1, 2], steps: "SW" },
    ],
  },
  {
    id: 5,
    title: "Cube 5",
    gridSize: 11,
    lives: 4,
    routes: [
      { id: "l5-straight-2", start: ["front", 9, 0], steps: "E" },
      { id: "l5-straight-3", start: ["back", 8, 1], steps: "EE" },
      { id: "l5-straight-4", start: ["right", 7, 2], steps: "EEE" },
      { id: "l5-3", start: ["back", 5, 1], steps: "SWWSSESWSWSES" },
      { id: "l5-4", start: ["top", 3, 0], steps: "NENWNENWESW" },
      { id: "l5-5", start: ["right", 2, 7], steps: "ESWWSSSSWWS" },
      { id: "l5-6", start: ["right", 7, 4], steps: "NWSWSSSEE" },
      { id: "l5-7", start: ["left", 2, 3], steps: "ENESEENNEN" },
      { id: "l5-8", start: ["bottom", 7, 9], steps: "ENNNWWSWWWNN" },
      { id: "l5-9", start: ["top", 10, 0], steps: "WNENSSWSSWW" },
      { id: "l5-10", start: ["top", 6, 3], steps: "WNENWWSS" },
      { id: "l5-11", start: ["top", 6, 8], steps: "NNNWWSWSESSEE" },
      { id: "l5-12", start: ["front", 0, 4], steps: "NENWWSS" },
      { id: "l5-13", start: ["bottom", 6, 4], steps: "NWWWWNNEENNN" },
      { id: "l5-14", start: ["right", 2, 5], steps: "SWNWSWSESWS" },
      { id: "l5-15", start: ["front", 10, 2], steps: "EENWWWWWWS" },
      { id: "l5-16", start: ["bottom", 0, 2], steps: "WNWWWNENNNW" },
      { id: "l5-17", start: ["right", 10, 0], steps: "ESSESSSSW" },
      { id: "l5-18", start: ["bottom", 0, 7], steps: "NWEESSENN" },
      { id: "l5-19", start: ["top", 8, 4], steps: "NEESEESWWN" },
      { id: "l5-20", start: ["front", 5, 9], steps: "NNNESSS" },
      { id: "l5-21", start: ["right", 8, 5], steps: "NESSWSE" },
      { id: "l5-22", start: ["back", 7, 5], steps: "ESWSEE" },
      { id: "l5-23", start: ["front", 2, 0], steps: "SSSEEESENEE" },
      { id: "l5-24", start: ["left", 0, 6], steps: "WNENWWWNWSWN" },
      { id: "l5-25", start: ["top", 4, 4], steps: "WWSSWW" },
      { id: "l5-26", start: ["front", 10, 5], steps: "WSWWSESS" },
      { id: "l5-27", start: ["left", 9, 1], steps: "WNNEEESWWW" },
      { id: "l5-28", start: ["back", 6, 7], steps: "NNWSSWSEE" },
      { id: "l5-29", start: ["back", 5, 9], steps: "SESWSEESENW" },
      { id: "l5-30", start: ["top", 7, 5], steps: "EESSSEEWWNWNE" },
      { id: "l5-31", start: ["back", 0, 7], steps: "WSESES" },
      { id: "l5-32", start: ["bottom", 1, 2], steps: "N" },
      { id: "l5-33", start: ["front", 4, 1], steps: "WSEENNEEENW" },
      { id: "l5-34", start: ["front", 3, 0], steps: "ENWWWWSSWN" },
      { id: "l5-35", start: ["bottom", 5, 6], steps: "WNE" },
      { id: "l5-36", start: ["bottom", 3, 9], steps: "ENW" },
      { id: "l5-37", start: ["back", 7, 9], steps: "NEEESEEENW" },
      { id: "l5-38", start: ["front", 9, 7], steps: "SS" },
      { id: "l5-39", start: ["right", 10, 9], steps: "WNWSWSSWSEEE" },
      { id: "l5-40", start: ["bottom", 6, 5], steps: "EN" },
      { id: "l5-41", start: ["bottom", 10, 3], steps: "WSWSEE" },
      { id: "l5-42", start: ["bottom", 2, 8], steps: "NNWSSWWW" },
      { id: "l5-43", start: ["bottom", 7, 3], steps: "NN" },
      { id: "l5-44", start: ["bottom", 3, 0], steps: "WNENNENWWWNW" },
      { id: "l5-45", start: ["left", 3, 4], steps: "SWWSEESW" },
      { id: "l5-46", start: ["right", 4, 3], steps: "ENWWWNEEN" },
      { id: "l5-47", start: ["left", 2, 4], steps: "WNWNEEN" },
      { id: "l5-48", start: ["front", 0, 7], steps: "SWWNWNENE" },
      { id: "l5-49", start: ["top", 9, 2], steps: "NESESEN" },
      { id: "l5-50", start: ["top", 2, 7], steps: "WW" },
      { id: "l5-51", start: ["right", 7, 8], steps: "WWWSES" },
      { id: "l5-52", start: ["right", 8, 3], steps: "EE" },
      { id: "l5-53", start: ["front", 9, 3], steps: "SWSWWWW" },
      { id: "l5-54", start: ["top", 1, 2], steps: "SWWSEN" },
      { id: "l5-55", start: ["bottom", 0, 1], steps: "WNES" },
      { id: "l5-56", start: ["bottom", 3, 2], steps: "EENNNE" },
      { id: "l5-57", start: ["left", 5, 2], steps: "NN" },
      { id: "l5-58", start: ["back", 10, 2], steps: "WSE" },
      { id: "l5-59", start: ["bottom", 9, 1], steps: "WNE" },
      { id: "l5-60", start: ["top", 3, 3], steps: "WNENWWW" },
      { id: "l5-61", start: ["right", 6, 9], steps: "S" },
      { id: "l5-62", start: ["back", 0, 10], steps: "WSNWS" },
      { id: "l5-63", start: ["front", 10, 4], steps: "NEEEESW" },
      { id: "l5-64", start: ["bottom", 9, 6], steps: "E" },
      { id: "l5-65", start: ["bottom", 6, 2], steps: "NNENEE" },
    ],
  },
  {
    id: 6,
    title: "Cube 6",
    gridSize: 12,
    lives: 4,
    routes: [
      { id: "l6-straight-2", start: ["front", 10, 0], steps: "E" },
      { id: "l6-straight-3", start: ["back", 9, 1], steps: "EE" },
      { id: "l6-straight-4", start: ["right", 8, 2], steps: "EEE" },
      { id: "l6-3", start: ["front", 10, 1], steps: "WWNENWWSSWS" },
      { id: "l6-4", start: ["front", 1, 9], steps: "WNWWWSESSSE" },
      { id: "l6-5", start: ["back", 3, 2], steps: "WSWSSSSSW" },
      { id: "l6-6", start: ["bottom", 7, 0], steps: "SSWWWNNW" },
      { id: "l6-7", start: ["right", 0, 6], steps: "WSEESESSEN" },
      { id: "l6-8", start: ["left", 8, 4], steps: "WSWWNENNWSWN" },
      { id: "l6-9", start: ["bottom", 5, 4], steps: "SWWWWWS" },
      { id: "l6-10", start: ["back", 9, 4], steps: "SWSSSWSWWSS" },
      { id: "l6-11", start: ["back", 5, 6], steps: "EENWNNNN" },
      { id: "l6-12", start: ["bottom", 7, 9], steps: "WWWSWNW" },
      { id: "l6-13", start: ["front", 1, 3], steps: "ESSSWWWWW" },
      { id: "l6-14", start: ["top", 5, 1], steps: "ESSSWWN" },
      { id: "l6-15", start: ["top", 7, 8], steps: "WWNNESE" },
      { id: "l6-16", start: ["right", 7, 8], steps: "SEENES" },
      { id: "l6-17", start: ["top", 2, 7], steps: "NNWNNWWE" },
      { id: "l6-18", start: ["front", 6, 0], steps: "WNENEEN" },
      { id: "l6-19", start: ["top", 10, 4], steps: "EEWWNSEWWNS" },
      { id: "l6-20", start: ["bottom", 9, 1], steps: "ENWWSSEESENNEW" },
      { id: "l6-21", start: ["back", 10, 0], steps: "WNENSSWN" },
      { id: "l6-22", start: ["right", 4, 4], steps: "ENESSEESSE" },
      { id: "l6-23", start: ["left", 11, 9], steps: "SE" },
      { id: "l6-24", start: ["top", 1, 8], steps: "WSESWS" },
      { id: "l6-25", start: ["right", 2, 1], steps: "EESWWWWNENW" },
      { id: "l6-26", start: ["top", 4, 7], steps: "NWSSWSSES" },
      { id: "l6-27", start: ["front", 6, 5], steps: "WSSSESS" },
      { id: "l6-28", start: ["left", 8, 6], steps: "NEEEENWWWN" },
      { id: "l6-29", start: ["right", 11, 10], steps: "SSWNWSW" },
      { id: "l6-30", start: ["right", 10, 3], steps: "EESSWWWNEE" },
      { id: "l6-31", start: ["bottom", 1, 0], steps: "NESSSWSSWWNW" },
      { id: "l6-32", start: ["bottom", 9, 7], steps: "WSWWNW" },
      { id: "l6-33", start: ["left", 0, 2], steps: "WSEENENW" },
      { id: "l6-34", start: ["top", 11, 5], steps: "WSSWN" },
      { id: "l6-35", start: ["top", 4, 11], steps: "SWSEESSESESSSS" },
      { id: "l6-36", start: ["back", 4, 10], steps: "NWSSESNWSWW" },
      { id: "l6-37", start: ["bottom", 9, 3], steps: "SWNWWSSE" },
      { id: "l6-38", start: ["top", 0, 7], steps: "ENWWESSSENNE" },
      { id: "l6-39", start: ["back", 11, 9], steps: "NENNNNES" },
      { id: "l6-40", start: ["left", 0, 9], steps: "SSWSEEESNE" },
      { id: "l6-41", start: ["left", 0, 1], steps: "N" },
      { id: "l6-42", start: ["top", 8, 3], steps: "ENEESESE" },
      { id: "l6-43", start: ["bottom", 11, 7], steps: "ENWNNWNENWNWS" },
      { id: "l6-44", start: ["back", 11, 7], steps: "NNWSS" },
      { id: "l6-45", start: ["back", 0, 1], steps: "EENENESWSWN" },
      { id: "l6-46", start: ["front", 2, 2], steps: "NNNWSSWN" },
      { id: "l6-47", start: ["left", 4, 10], steps: "SSEESEENNE" },
      { id: "l6-48", start: ["top", 7, 3], steps: "SESSSSE" },
      { id: "l6-49", start: ["bottom", 11, 10], steps: "ENWSWSWSE" },
      { id: "l6-50", start: ["back", 2, 11], steps: "NNWWSES" },
      { id: "l6-51", start: ["front", 2, 7], steps: "WSESENNES" },
      { id: "l6-52", start: ["front", 1, 2], steps: "W" },
      { id: "l6-53", start: ["left", 1, 7], steps: "ENEEES" },
      { id: "l6-54", start: ["right", 4, 3], steps: "WW" },
      { id: "l6-55", start: ["bottom", 0, 3], steps: "WNNNNE" },
      { id: "l6-56", start: ["bottom", 6, 1], steps: "WNENE" },
      { id: "l6-57", start: ["back", 6, 7], steps: "WWSWWNENWNEEN" },
      { id: "l6-58", start: ["top", 5, 3], steps: "NW" },
      { id: "l6-59", start: ["left", 3, 8], steps: "SWNWSSSENES" },
      { id: "l6-60", start: ["bottom", 8, 5], steps: "SENE" },
      { id: "l6-61", start: ["left", 9, 2], steps: "E" },
      { id: "l6-62", start: ["front", 11, 1], steps: "SWWWWSE" },
      { id: "l6-63", start: ["right", 1, 9], steps: "SWNWWNNWSS" },
      { id: "l6-64", start: ["front", 8, 4], steps: "SSSSSWSESENES" },
      { id: "l6-65", start: ["right", 3, 8], steps: "NESSS" },
      { id: "l6-66", start: ["bottom", 10, 7], steps: "NE" },
      { id: "l6-67", start: ["left", 8, 0], steps: "EESEN" },
      { id: "l6-68", start: ["right", 1, 6], steps: "NESENNW" },
      { id: "l6-69", start: ["left", 1, 0], steps: "NSEN" },
      { id: "l6-70", start: ["front", 5, 11], steps: "NWS" },
      { id: "l6-71", start: ["front", 9, 6], steps: "ENWNNEE" },
      { id: "l6-72", start: ["back", 6, 11], steps: "NES" },
      { id: "l6-73", start: ["bottom", 2, 10], steps: "WW" },
      { id: "l6-74", start: ["back", 5, 5], steps: "NN" },
      { id: "l6-75", start: ["top", 11, 8], steps: "WSSSE" },
      { id: "l6-76", start: ["left", 4, 9], steps: "NEENNESSSWWS" },
      { id: "l6-77", start: ["top", 5, 0], steps: "EENSSEN" },
    ],
  },
  {
    id: 7,
    title: "Cube 7",
    gridSize: 12,
    lives: 3,
    routes: [
      { id: "l7-straight-2", start: ["front", 10, 0], steps: "E" },
      { id: "l7-straight-3", start: ["back", 9, 1], steps: "EE" },
      { id: "l7-straight-4", start: ["right", 8, 2], steps: "EEE" },
      { id: "l7-3", start: ["top", 4, 8], steps: "SSWWWNNW" },
      { id: "l7-4", start: ["front", 0, 10], steps: "ENNWWNENWWS" },
      { id: "l7-5", start: ["front", 4, 6], steps: "ESSENNEEE" },
      { id: "l7-6", start: ["front", 4, 0], steps: "WNWSSSW" },
      { id: "l7-7", start: ["back", 1, 3], steps: "NNENWNEN" },
      { id: "l7-8", start: ["front", 6, 0], steps: "WNNNENEE" },
      { id: "l7-9", start: ["left", 6, 9], steps: "ENENWNNENEEE" },
      { id: "l7-10", start: ["bottom", 8, 6], steps: "EESWWWWN" },
      { id: "l7-11", start: ["bottom", 10, 10], steps: "WNNWSSWSESE" },
      { id: "l7-12", start: ["top", 11, 4], steps: "WSSSEEWNSSESS" },
      { id: "l7-13", start: ["bottom", 9, 11], steps: "ESWSENEENNNES" },
      { id: "l7-14", start: ["top", 2, 7], steps: "EEENWNEENWWW" },
      { id: "l7-15", start: ["top", 10, 2], steps: "ESEWSEE" },
      { id: "l7-16", start: ["bottom", 5, 1], steps: "SSSSWW" },
      { id: "l7-17", start: ["right", 9, 0], steps: "E" },
      { id: "l7-18", start: ["front", 3, 11], steps: "NWSSEESSW" },
      { id: "l7-19", start: ["front", 2, 4], steps: "SWSSEESWSEE" },
      { id: "l7-20", start: ["back", 0, 4], steps: "NWSSEESWSWW" },
      { id: "l7-21", start: ["right", 0, 6], steps: "WSWSEEEEESEEN" },
      { id: "l7-22", start: ["top", 4, 0], steps: "ENESSWWSESWS" },
      { id: "l7-23", start: ["bottom", 4, 3], steps: "SWNWNWWNN" },
      { id: "l7-24", start: ["bottom", 2, 5], steps: "WSSENESSENNES" },
      { id: "l7-25", start: ["right", 7, 5], steps: "SSWNNNWSWSWNW" },
      { id: "l7-26", start: ["top", 1, 4], steps: "NEEEENW" },
      { id: "l7-27", start: ["top", 7, 6], steps: "SENENWNWNWN" },
      { id: "l7-28", start: ["back", 9, 4], steps: "ENWNEEENN" },
      { id: "l7-29", start: ["front", 7, 8], steps: "ENESSE" },
      { id: "l7-30", start: ["bottom", 6, 11], steps: "WSNWNEESEEE" },
      { id: "l7-31", start: ["top", 1, 11], steps: "WSESWWN" },
      { id: "l7-32", start: ["bottom", 1, 1], steps: "NNWWWNWS" },
      { id: "l7-33", start: ["top", 2, 0], steps: "NWNSWSWNNW" },
      { id: "l7-34", start: ["right", 6, 0], steps: "SWWSESWWW" },
      { id: "l7-35", start: ["back", 3, 5], steps: "SESSENNEEE" },
      { id: "l7-36", start: ["left", 3, 0], steps: "NSSWSSSESWWNN" },
      { id: "l7-37", start: ["bottom", 8, 4], steps: "SWNNENEN" },
      { id: "l7-38", start: ["right", 9, 5], steps: "SSSWWSSENE" },
      { id: "l7-39", start: ["back", 10, 5], steps: "ENNEENNNES" },
      { id: "l7-40", start: ["bottom", 11, 10], steps: "EW" },
      { id: "l7-41", start: ["front", 6, 5], steps: "NWNWWNE" },
      { id: "l7-42", start: ["back", 10, 8], steps: "EESSSESSESE" },
      { id: "l7-43", start: ["front", 2, 3], steps: "W" },
      { id: "l7-44", start: ["bottom", 11, 9], steps: "WNEEWWNWS" },
      { id: "l7-45", start: ["right", 4, 10], steps: "SWNWWSW" },
      { id: "l7-46", start: ["front", 1, 4], steps: "WNNWWN" },
      { id: "l7-47", start: ["left", 5, 5], steps: "SSWSWWS" },
      { id: "l7-48", start: ["left", 0, 6], steps: "SESSSEEEEES" },
      { id: "l7-49", start: ["bottom", 2, 4], steps: "WW" },
      { id: "l7-50", start: ["front", 4, 10], steps: "SENE" },
      { id: "l7-51", start: ["bottom", 5, 0], steps: "ENE" },
      { id: "l7-52", start: ["back", 0, 2], steps: "NWN" },
      { id: "l7-53", start: ["front", 8, 9], steps: "WSE" },
      { id: "l7-54", start: ["top", 4, 1], steps: "EE" },
      { id: "l7-55", start: ["front", 10, 6], steps: "NEENNWWSE" },
      { id: "l7-56", start: ["front", 11, 9], steps: "ESWS" },
      { id: "l7-57", start: ["top", 10, 11], steps: "NNNWSS" },
      { id: "l7-58", start: ["back", 4, 1], steps: "SSSWNN" },
      { id: "l7-59", start: ["back", 3, 1], steps: "N" },
      { id: "l7-60", start: ["front", 10, 11], steps: "NWSWSEEE" },
      { id: "l7-61", start: ["front", 0, 9], steps: "WWNWNNNEE" },
      { id: "l7-62", start: ["bottom", 1, 10], steps: "EENW" },
      { id: "l7-63", start: ["back", 4, 0], steps: "ENESSEN" },
      { id: "l7-64", start: ["back", 8, 4], steps: "WSEESESE" },
      { id: "l7-65", start: ["top", 0, 9], steps: "WSWN" },
      { id: "l7-66", start: ["left", 2, 3], steps: "NESSW" },
      { id: "l7-67", start: ["top", 2, 4], steps: "SWSSW" },
      { id: "l7-68", start: ["bottom", 7, 8], steps: "SWNWSWS" },
      { id: "l7-69", start: ["bottom", 6, 1], steps: "SENN" },
      { id: "l7-70", start: ["left", 0, 4], steps: "ESW" },
      { id: "l7-71", start: ["front", 3, 1], steps: "EE" },
      { id: "l7-72", start: ["right", 5, 6], steps: "SWWWWW" },
      { id: "l7-73", start: ["bottom", 2, 8], steps: "W" },
      { id: "l7-74", start: ["front", 7, 0], steps: "SESWSESWSEEN" },
      { id: "l7-75", start: ["top", 9, 4], steps: "NN" },
      { id: "l7-76", start: ["top", 8, 0], steps: "ESEE" },
      { id: "l7-77", start: ["right", 2, 11], steps: "SSWWSSE" },
      { id: "l7-78", start: ["left", 7, 4], steps: "NEEE" },
      { id: "l7-79", start: ["top", 9, 11], steps: "WSESEEEN" },
      { id: "l7-80", start: ["bottom", 10, 4], steps: "E" },
      { id: "l7-81", start: ["left", 9, 9], steps: "WSWS" },
      { id: "l7-82", start: ["bottom", 1, 3], steps: "W" },
      { id: "l7-83", start: ["bottom", 1, 9], steps: "W" },
    ],
  },
  {
    id: 8,
    title: "Cube 8",
    gridSize: 13,
    lives: 3,
    routes: [
      { id: "l8-straight-2", start: ["front", 11, 0], steps: "E" },
      { id: "l8-straight-3", start: ["back", 10, 1], steps: "EE" },
      { id: "l8-straight-4", start: ["right", 9, 2], steps: "EEE" },
      { id: "l8-3", start: ["top", 1, 5], steps: "SSWWSE" },
      { id: "l8-4", start: ["top", 0, 10], steps: "WSSENNNES" },
      { id: "l8-5", start: ["front", 6, 0], steps: "WSWSEEEESWWW" },
      { id: "l8-6", start: ["back", 8, 9], steps: "SWSWWNNENW" },
      { id: "l8-7", start: ["front", 3, 6], steps: "WNWNWSWSES" },
      { id: "l8-8", start: ["front", 6, 10], steps: "WSWSWSWNWSWWW" },
      { id: "l8-9", start: ["bottom", 12, 11], steps: "EWSNENENW" },
      { id: "l8-10", start: ["bottom", 8, 0], steps: "ENNWSWWNENEENN" },
      { id: "l8-11", start: ["bottom", 8, 6], steps: "NESSSEEEENNW" },
      { id: "l8-12", start: ["left", 10, 5], steps: "SWWSEESWSE" },
      { id: "l8-13", start: ["right", 10, 6], steps: "NWNWSSSSWN" },
      { id: "l8-14", start: ["left", 3, 1], steps: "NNEEEESE" },
      { id: "l8-15", start: ["back", 12, 10], steps: "ESWWSWWSW" },
      { id: "l8-16", start: ["back", 1, 8], steps: "EEENNNWW" },
      { id: "l8-17", start: ["left", 0, 7], steps: "ENWWNNW" },
      { id: "l8-18", start: ["back", 6, 4], steps: "WNWWSWNNE" },
      { id: "l8-19", start: ["front", 7, 5], steps: "SEENNNNNES" },
      { id: "l8-20", start: ["right", 0, 2], steps: "SWWSEES" },
      { id: "l8-21", start: ["left", 0, 8], steps: "SEEENNNES" },
      { id: "l8-22", start: ["right", 4, 0], steps: "ESWSWWSE" },
      { id: "l8-23", start: ["bottom", 11, 4], steps: "ENNENNNWS" },
      { id: "l8-24", start: ["back", 3, 10], steps: "SSESENES" },
      { id: "l8-25", start: ["back", 9, 2], steps: "SENEESESE" },
      { id: "l8-26", start: ["top", 12, 6], steps: "WNNWWSSSWNN" },
      { id: "l8-27", start: ["back", 0, 1], steps: "WWWNNWW" },
      { id: "l8-28", start: ["top", 12, 11], steps: "WSWSWNNENNW" },
      { id: "l8-29", start: ["bottom", 8, 4], steps: "ENNNENNNNNNES" },
      { id: "l8-30", start: ["bottom", 5, 10], steps: "NENENWNN" },
      { id: "l8-31", start: ["right", 7, 11], steps: "SSNENNNNNWSS" },
      { id: "l8-32", start: ["back", 12, 0], steps: "NSSWSSSSE" },
      { id: "l8-33", start: ["back", 0, 3], steps: "NESSSW" },
      { id: "l8-34", start: ["top", 8, 2], steps: "NWNWNENSESES" },
      { id: "l8-35", start: ["top", 3, 8], steps: "EENWWNENWWSS" },
      { id: "l8-36", start: ["bottom", 10, 7], steps: "ENWNNNENN" },
      { id: "l8-37", start: ["left", 7, 12], steps: "NEESSNEEEENWW" },
      { id: "l8-38", start: ["right", 3, 5], steps: "WWNEEES" },
      { id: "l8-39", start: ["back", 10, 6], steps: "ENWWSSSWWNEN" },
      { id: "l8-40", start: ["bottom", 7, 10], steps: "SSWNWS" },
      { id: "l8-41", start: ["top", 9, 10], steps: "WNW" },
      { id: "l8-42", start: ["left", 6, 3], steps: "SSSWNNNWNENWN" },
      { id: "l8-43", start: ["bottom", 5, 2], steps: "SWWSWW" },
      { id: "l8-44", start: ["left", 0, 0], steps: "SSEN" },
      { id: "l8-45", start: ["right", 6, 0], steps: "SSSSWSESENN" },
      { id: "l8-46", start: ["left", 12, 10], steps: "NEESENNW" },
      { id: "l8-47", start: ["front", 12, 8], steps: "ENWNEEESSES" },
      { id: "l8-48", start: ["top", 6, 12], steps: "WNEESSSEN" },
      { id: "l8-49", start: ["left", 12, 11], steps: "WNWWWWNENWWS" },
      { id: "l8-50", start: ["top", 4, 0], steps: "WNENSWN" },
      { id: "l8-51", start: ["back", 4, 11], steps: "NNW" },
      { id: "l8-52", start: ["front", 4, 0], steps: "NWSW" },
      { id: "l8-53", start: ["back", 5, 12], steps: "EEESNNNW" },
      { id: "l8-54", start: ["front", 11, 2], steps: "ENEEENNNWNE" },
      { id: "l8-55", start: ["bottom", 12, 1], steps: "EW" },
      { id: "l8-56", start: ["top", 12, 3], steps: "SSESSSEN" },
      { id: "l8-57", start: ["right", 12, 10], steps: "NENNWWSE" },
      { id: "l8-58", start: ["top", 10, 5], steps: "SSE" },
      { id: "l8-59", start: ["top", 0, 12], steps: "WSEEEESW" },
      { id: "l8-60", start: ["left", 5, 9], steps: "SESSSESSSS" },
      { id: "l8-61", start: ["front", 7, 4], steps: "WWWNWW" },
      { id: "l8-62", start: ["right", 3, 1], steps: "N" },
      { id: "l8-63", start: ["back", 12, 12], steps: "SWENES" },
      { id: "l8-64", start: ["right", 3, 12], steps: "NNES" },
      { id: "l8-65", start: ["top", 3, 9], steps: "SESWWS" },
      { id: "l8-66", start: ["back", 6, 2], steps: "ENWWNWNE" },
      { id: "l8-67", start: ["top", 1, 10], steps: "ENW" },
      { id: "l8-68", start: ["back", 0, 4], steps: "WNWWSESSE" },
      { id: "l8-69", start: ["bottom", 7, 6], steps: "NNWNEN" },
      { id: "l8-70", start: ["left", 1, 10], steps: "EES" },
      { id: "l8-71", start: ["left", 11, 4], steps: "WWSWNWNEE" },
      { id: "l8-72", start: ["left", 7, 5], steps: "SSWWSWSS" },
      { id: "l8-73", start: ["bottom", 4, 8], steps: "ENNNNWSWW" },
      { id: "l8-74", start: ["back", 11, 10], steps: "WNNNEESWSE" },
      { id: "l8-75", start: ["back", 2, 0], steps: "NENSEEN" },
      { id: "l8-76", start: ["top", 6, 4], steps: "EENENNEEEEE" },
      { id: "l8-77", start: ["bottom", 8, 3], steps: "NNWN" },
      { id: "l8-78", start: ["top", 2, 8], steps: "W" },
      { id: "l8-79", start: ["bottom", 6, 0], steps: "SWN" },
      { id: "l8-80", start: ["front", 6, 6], steps: "WWSSSSWSWWWS" },
      { id: "l8-81", start: ["bottom", 3, 10], steps: "SWWWNNNNWNWS" },
      { id: "l8-82", start: ["right", 1, 11], steps: "WNNWSS" },
      { id: "l8-83", start: ["bottom", 12, 12], steps: "ENEEESW" },
      { id: "l8-84", start: ["right", 9, 0], steps: "SWN" },
      { id: "l8-85", start: ["back", 1, 7], steps: "EENW" },
      { id: "l8-86", start: ["top", 8, 11], steps: "S" },
      { id: "l8-87", start: ["left", 4, 4], steps: "SWWW" },
      { id: "l8-88", start: ["front", 11, 6], steps: "SWNNE" },
      { id: "l8-89", start: ["left", 10, 11], steps: "S" },
    ],
  },
  {
    id: 9,
    title: "Cube 9",
    gridSize: 14,
    lives: 3,
    routes: [
      { id: "l9-straight-2", start: ["front", 12, 0], steps: "E" },
      { id: "l9-straight-3", start: ["back", 11, 1], steps: "EE" },
      { id: "l9-straight-4", start: ["right", 10, 2], steps: "EEE" },
      { id: "l9-3", start: ["back", 4, 6], steps: "SWWWNWNWSSESE" },
      { id: "l9-4", start: ["back", 3, 6], steps: "WNEENESSEN" },
      { id: "l9-5", start: ["left", 10, 1], steps: "SEENESSWS" },
      { id: "l9-6", start: ["front", 0, 8], steps: "WNNENWNEEEN" },
      { id: "l9-7", start: ["back", 10, 0], steps: "WNENWNEENSSE" },
      { id: "l9-8", start: ["bottom", 6, 1], steps: "WWNWNENNES" },
      { id: "l9-9", start: ["right", 6, 13], steps: "NEESSNWSSES" },
      { id: "l9-10", start: ["back", 7, 8], steps: "SWSESWS" },
      { id: "l9-11", start: ["left", 4, 6], steps: "SWNNNNWSS" },
      { id: "l9-12", start: ["back", 10, 1], steps: "WWSEESW" },
      { id: "l9-13", start: ["top", 11, 11], steps: "ENESEWWSS" },
      { id: "l9-14", start: ["right", 1, 6], steps: "SWNWSSEES" },
      { id: "l9-15", start: ["front", 9, 9], steps: "NNNENENNNES" },
      { id: "l9-16", start: ["bottom", 0, 5], steps: "ENEENWWNNW" },
      { id: "l9-17", start: ["front", 5, 4], steps: "WSESWSSWNWWSSES" },
      { id: "l9-18", start: ["front", 8, 6], steps: "NNWSWNNWWWNEN" },
      { id: "l9-19", start: ["bottom", 2, 9], steps: "ENNWSWNW" },
      { id: "l9-20", start: ["bottom", 6, 0], steps: "WNEESSE" },
      { id: "l9-21", start: ["bottom", 8, 6], steps: "WNNWWNWSSEESW" },
      { id: "l9-22", start: ["back", 0, 4], steps: "WWSSWNW" },
      { id: "l9-23", start: ["top", 6, 11], steps: "NWNWSSWWNNWS" },
      { id: "l9-24", start: ["left", 0, 2], steps: "NNENSSESEN" },
      { id: "l9-25", start: ["bottom", 4, 12], steps: "SESWSESWW" },
      { id: "l9-26", start: ["bottom", 12, 6], steps: "ENEWSNNWWWNWS" },
      { id: "l9-27", start: ["right", 3, 8], steps: "EEEENNNEN" },
      { id: "l9-28", start: ["left", 2, 0], steps: "SSENNENSE" },
      { id: "l9-29", start: ["front", 3, 10], steps: "SSWSSWWNW" },
      { id: "l9-30", start: ["bottom", 8, 8], steps: "NEESWSESWW" },
      { id: "l9-31", start: ["right", 7, 4], steps: "WNENWWNNNNW" },
      { id: "l9-32", start: ["back", 8, 7], steps: "NEESSWWSSSESS" },
      { id: "l9-33", start: ["back", 1, 9], steps: "ENEEESSSWNNWS" },
      { id: "l9-34", start: ["right", 11, 1], steps: "ENEEENESWWSE" },
      { id: "l9-35", start: ["left", 13, 10], steps: "WWNNNWSSSS" },
      { id: "l9-36", start: ["back", 12, 7], steps: "SWSSSWSE" },
      { id: "l9-37", start: ["top", 1, 11], steps: "SSSSESW" },
      { id: "l9-38", start: ["top", 9, 1], steps: "ESSESWWSSSS" },
      { id: "l9-39", start: ["left", 5, 0], steps: "SENNSEENESSW" },
      { id: "l9-40", start: ["front", 9, 5], steps: "N" },
      { id: "l9-41", start: ["right", 3, 6], steps: "NENESESWWSWWSS" },
      { id: "l9-42", start: ["top", 0, 0], steps: "NWNSSEN" },
      { id: "l9-43", start: ["front", 11, 9], steps: "WSWSWSS" },
      { id: "l9-44", start: ["left", 4, 13], steps: "EENNNWSW" },
      { id: "l9-45", start: ["bottom", 1, 13], steps: "WNEESESE" },
      { id: "l9-46", start: ["front", 12, 5], steps: "NENNNWWNNE" },
      { id: "l9-47", start: ["right", 13, 12], steps: "SESWSESWSNNW" },
      { id: "l9-48", start: ["back", 12, 13], steps: "NNES" },
      { id: "l9-49", start: ["top", 8, 1], steps: "SSWWSEESSS" },
      { id: "l9-50", start: ["right", 6, 11], steps: "EENWWWSWNNWS" },
      { id: "l9-51", start: ["front", 2, 0], steps: "NNESSENENE" },
      { id: "l9-52", start: ["left", 3, 10], steps: "ENNEEENEENNNN" },
      { id: "l9-53", start: ["back", 6, 4], steps: "NESSEE" },
      { id: "l9-54", start: ["front", 10, 7], steps: "SENNES" },
      { id: "l9-55", start: ["right", 10, 12], steps: "EESSWWNEE" },
      { id: "l9-56", start: ["bottom", 4, 6], steps: "WNWSWWWNNNNES" },
      { id: "l9-57", start: ["top", 7, 6], steps: "SSSESESSE" },
      { id: "l9-58", start: ["left", 2, 9], steps: "ENWNWWWSSEENW" },
      { id: "l9-59", start: ["back", 3, 4], steps: "WWNEENW" },
      { id: "l9-60", start: ["front", 11, 13], steps: "ENNEEESSSWN" },
      { id: "l9-61", start: ["front", 10, 4], steps: "NN" },
      { id: "l9-62", start: ["left", 8, 11], steps: "ESWSESNWNENE" },
      { id: "l9-63", start: ["back", 13, 2], steps: "WWSEEEESW" },
      { id: "l9-64", start: ["front", 9, 3], steps: "WWNEEN" },
      { id: "l9-65", start: ["back", 2, 10], steps: "WSWWWWWWNE" },
      { id: "l9-66", start: ["top", 8, 11], steps: "WSESSWNWSSWN" },
      { id: "l9-67", start: ["back", 2, 12], steps: "WW" },
      { id: "l9-68", start: ["bottom", 0, 11], steps: "ENWWWW" },
      { id: "l9-69", start: ["right", 13, 1], steps: "EESW" },
      { id: "l9-70", start: ["left", 8, 1], steps: "NENSWEENS" },
      { id: "l9-71", start: ["right", 11, 10], steps: "NENWNWWN" },
      { id: "l9-72", start: ["left", 5, 12], steps: "WWNWWNWS" },
      { id: "l9-73", start: ["left", 7, 6], steps: "ENWWNENN" },
      { id: "l9-74", start: ["top", 1, 8], steps: "W" },
      { id: "l9-75", start: ["bottom", 11, 1], steps: "N" },
      { id: "l9-76", start: ["back", 0, 3], steps: "WWWSWNWWN" },
      { id: "l9-77", start: ["left", 11, 6], steps: "ESSSEESESSS" },
      { id: "l9-78", start: ["right", 2, 6], steps: "NWNNW" },
      { id: "l9-79", start: ["right", 5, 12], steps: "WWNWS" },
      { id: "l9-80", start: ["top", 5, 5], steps: "WNENNENWWWN" },
      { id: "l9-81", start: ["right", 9, 2], steps: "NWN" },
      { id: "l9-82", start: ["bottom", 10, 12], steps: "NWSS" },
      { id: "l9-83", start: ["right", 10, 1], steps: "NWNWNE" },
      { id: "l9-84", start: ["back", 8, 3], steps: "SEESE" },
      { id: "l9-85", start: ["back", 11, 4], steps: "EE" },
      { id: "l9-86", start: ["top", 13, 5], steps: "WWSE" },
      { id: "l9-87", start: ["left", 2, 6], steps: "W" },
      { id: "l9-88", start: ["front", 10, 1], steps: "N" },
      { id: "l9-89", start: ["right", 12, 10], steps: "E" },
    ],
  },
  {
    id: 10,
    title: "Cube 10",
    gridSize: 14,
    lives: 3,
    routes: [
      { id: "l10-straight-2", start: ["front", 12, 0], steps: "E" },
      { id: "l10-straight-3", start: ["back", 11, 1], steps: "EE" },
      { id: "l10-straight-4", start: ["right", 10, 2], steps: "EEE" },
      { id: "l10-3", start: ["front", 7, 7], steps: "NWNENNENWNN" },
      { id: "l10-4", start: ["bottom", 7, 12], steps: "NEESENEENWWNW" },
      { id: "l10-5", start: ["left", 7, 3], steps: "NNWNENNESE" },
      { id: "l10-6", start: ["left", 12, 0], steps: "NNESSSENESSWS" },
      { id: "l10-7", start: ["top", 10, 5], steps: "SEESSEESWSWS" },
      { id: "l10-8", start: ["back", 10, 5], steps: "WNENNNNE" },
      { id: "l10-9", start: ["left", 1, 0], steps: "NSWESWWSEEEEES" },
      { id: "l10-10", start: ["back", 9, 1], steps: "NWNEENSWSS" },
      { id: "l10-11", start: ["right", 7, 10], steps: "NNNWNENWNEEE" },
      { id: "l10-12", start: ["left", 7, 10], steps: "NENWWWWSWNNE" },
      { id: "l10-13", start: ["bottom", 4, 6], steps: "SENNWNWNN" },
      { id: "l10-14", start: ["right", 11, 4], steps: "SESSSESWSE" },
      { id: "l10-15", start: ["left", 5, 12], steps: "ENNNWSWW" },
      { id: "l10-16", start: ["right", 2, 12], steps: "ESSWSWSSWN" },
      { id: "l10-17", start: ["left", 8, 4], steps: "SESWSESSENN" },
      { id: "l10-18", start: ["top", 9, 1], steps: "SEESWWSSWWSSWSW" },
      { id: "l10-19", start: ["bottom", 3, 10], steps: "ESEENEENWN" },
      { id: "l10-20", start: ["left", 10, 0], steps: "SWNNEEEN" },
      { id: "l10-21", start: ["back", 13, 11], steps: "WSSESEENWNENW" },
      { id: "l10-22", start: ["left", 12, 7], steps: "EESSWSESE" },
      { id: "l10-23", start: ["left", 3, 6], steps: "NEENWWNWS" },
      { id: "l10-24", start: ["front", 13, 5], steps: "WSWWNNEE" },
      { id: "l10-25", start: ["right", 13, 3], steps: "WWWWWNWNWNNN" },
      { id: "l10-26", start: ["back", 13, 9], steps: "WWWNNENESSEEN" },
      { id: "l10-27", start: ["back", 10, 6], steps: "WSSWNWSWS" },
      { id: "l10-28", start: ["bottom", 0, 12], steps: "WNNWNWWWWS" },
      { id: "l10-29", start: ["bottom", 4, 2], steps: "ESEENESSSSEN" },
      { id: "l10-30", start: ["back", 1, 9], steps: "ENNWNENENNN" },
      { id: "l10-31", start: ["front", 4, 5], steps: "ESWSESSENES" },
      { id: "l10-32", start: ["front", 9, 2], steps: "EESEEENESENNW" },
      { id: "l10-33", start: ["bottom", 1, 3], steps: "NWNWWNENNWWS" },
      { id: "l10-34", start: ["top", 6, 5], steps: "SWNNNENWWS" },
      { id: "l10-35", start: ["right", 5, 3], steps: "WSWSSESWWWSWWWS" },
      { id: "l10-36", start: ["right", 3, 1], steps: "NWNNNWSW" },
      { id: "l10-37", start: ["top", 5, 13], steps: "WSSESSSWNWS" },
      { id: "l10-38", start: ["bottom", 6, 1], steps: "ENNESESEEN" },
      { id: "l10-39", start: ["right", 1, 13], steps: "SSWNNEEWWWNENE" },
      { id: "l10-40", start: ["bottom", 6, 0], steps: "NWNWSSSEN" },
      { id: "l10-41", start: ["left", 11, 5], steps: "NNNEESEN" },
      { id: "l10-42", start: ["bottom", 8, 8], steps: "NESENESSENNEENE" },
      { id: "l10-43", start: ["left", 2, 11], steps: "NWNENWNNNNW" },
      { id: "l10-44", start: ["right", 11, 0], steps: "ESENNWNW" },
      { id: "l10-45", start: ["back", 3, 8], steps: "EENWNNNNNN" },
      { id: "l10-46", start: ["bottom", 3, 11], steps: "SS" },
      { id: "l10-47", start: ["right", 5, 4], steps: "SSSSS" },
      { id: "l10-48", start: ["front", 6, 0], steps: "NNEESSEESEN" },
      { id: "l10-49", start: ["front", 13, 7], steps: "WWSSWSSS" },
      { id: "l10-50", start: ["top", 2, 6], steps: "ESENNW" },
      { id: "l10-51", start: ["top", 11, 9], steps: "WNWSWSEESSE" },
      { id: "l10-52", start: ["top", 3, 3], steps: "WWNNEEENW" },
      { id: "l10-53", start: ["back", 5, 4], steps: "SENNNENN" },
      { id: "l10-54", start: ["back", 8, 10], steps: "ENWWSWWNWSSWWW" },
      { id: "l10-55", start: ["top", 10, 4], steps: "ESE" },
      { id: "l10-56", start: ["left", 9, 4], steps: "ENNWSWN" },
      { id: "l10-57", start: ["right", 6, 8], steps: "SSWSEEEES" },
      { id: "l10-58", start: ["bottom", 8, 12], steps: "SWSESWSNWWNWS" },
      { id: "l10-59", start: ["left", 0, 2], steps: "WWSESWSE" },
      { id: "l10-60", start: ["bottom", 13, 10], steps: "NEENNNWWNEEESS" },
      { id: "l10-61", start: ["left", 9, 11], steps: "WSESESSESENNN" },
      { id: "l10-62", start: ["right", 2, 4], steps: "WSESW" },
      { id: "l10-63", start: ["front", 0, 5], steps: "SWWNENEESSSSES" },
      { id: "l10-64", start: ["right", 13, 6], steps: "SESSSSWS" },
      { id: "l10-65", start: ["bottom", 3, 0], steps: "WSWNWWNEEESW" },
      { id: "l10-66", start: ["right", 2, 8], steps: "SSSENNNES" },
      { id: "l10-67", start: ["left", 4, 0], steps: "SENNEENWW" },
      { id: "l10-68", start: ["back", 7, 11], steps: "EES" },
      { id: "l10-69", start: ["right", 4, 10], steps: "S" },
      { id: "l10-70", start: ["back", 0, 12], steps: "EEESW" },
      { id: "l10-71", start: ["top", 2, 0], steps: "W" },
      { id: "l10-72", start: ["top", 11, 11], steps: "ESEEW" },
      { id: "l10-73", start: ["right", 11, 1], steps: "WWNNWNE" },
      { id: "l10-74", start: ["front", 1, 9], steps: "SEES" },
      { id: "l10-75", start: ["back", 0, 4], steps: "EENWWNNESEN" },
      { id: "l10-76", start: ["top", 6, 4], steps: "EENWNEN" },
      { id: "l10-77", start: ["back", 5, 13], steps: "WSEEE" },
      { id: "l10-78", start: ["right", 12, 11], steps: "SS" },
      { id: "l10-79", start: ["top", 5, 12], steps: "NNEESEESSE" },
      { id: "l10-80", start: ["left", 5, 11], steps: "WWSWSSNNEEEENW" },
      { id: "l10-81", start: ["left", 7, 11], steps: "SS" },
      { id: "l10-82", start: ["front", 10, 3], steps: "WS" },
      { id: "l10-83", start: ["left", 8, 13], steps: "SSEESSWNW" },
      { id: "l10-84", start: ["right", 6, 12], steps: "SWNWS" },
      { id: "l10-85", start: ["top", 11, 13], steps: "EE" },
      { id: "l10-86", start: ["front", 10, 8], steps: "NWS" },
      { id: "l10-87", start: ["front", 4, 8], steps: "WSESSENEEENES" },
      { id: "l10-88", start: ["front", 3, 5], steps: "SWNNNWNNW" },
      { id: "l10-89", start: ["left", 8, 1], steps: "N" },
    ],
  },
];
export const CAMPAIGN_LAYOUTS: readonly LevelDefinition[] = FROZEN_LAYOUTS.map(
  (layout) => ({
    ...layout,
    arrows: layout.routes.map((route) => ({
      id: route.id,
      path: decodeRoute(route, layout.gridSize),
    })),
  }),
);
